import { cleanup, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it } from 'vitest'
import { ServiceAssessmentWizard } from '../components/ServiceAssessmentWizard'

afterEach(cleanup)

describe('industrial service wizard', () => {
  it('completes an installed fire alarm path through result and quote intent', async () => {
    const user = userEvent.setup()
    render(<ServiceAssessmentWizard serviceId="fire-alarm-servicing" />)
    await user.selectOptions(screen.getByLabelText('Business or industry'), 'manufacturing')
    await user.click(screen.getByText('Conventional panel and zones'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.click(screen.getByText('Periodic service is due or overdue'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.selectOptions(screen.getByLabelText('Approximate site size'), 'small')
    await user.selectOptions(screen.getByLabelText('Fire risk assessment, logbook and previous service records'), 'partial')
    await user.selectOptions(screen.getByLabelText('Current alarm service position'), 'overdue-or-unknown')
    await user.selectOptions(screen.getByLabelText('Reason for commissioning'), 'first-examination')
    await user.selectOptions(screen.getByLabelText('Region'), 'london')
    await user.selectOptions(screen.getByLabelText('Desired timescale'), 'one-month')
    await user.click(screen.getByRole('button', { name: 'See my result' }))
    expect(screen.getByRole('heading', { name: /Fire alarm servicing is likely to be relevant/i })).toBeInTheDocument()
    expect(screen.getAllByText(/Evidence found/i)).toHaveLength(3)
    await user.click(screen.getByRole('button', { name: 'Continue with my project brief' }))
    expect(screen.getByRole('heading', { name: 'Who should we contact about this project?' })).toBeInTheDocument()
  })

  it('completes the emergency-lighting path through result and quote intent', async () => {
    const user = userEvent.setup()
    render(<ServiceAssessmentWizard serviceId="emergency-lighting" />)
    await user.selectOptions(screen.getByLabelText('Business or industry'), 'manufacturing')
    await user.click(screen.getByText('Self-contained emergency luminaires'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.click(screen.getByText('A scheduled function or duration test is due'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.selectOptions(screen.getByLabelText('Approximate site size'), 'small')
    await user.selectOptions(screen.getByLabelText('Fire risk assessment, asset schedule and test log'), 'partial')
    await user.selectOptions(screen.getByLabelText('Current emergency-lighting testing position'), 'overdue-or-unknown')
    await user.selectOptions(screen.getByLabelText('Reason for commissioning'), 'first-examination')
    await user.selectOptions(screen.getByLabelText('Region'), 'london')
    await user.selectOptions(screen.getByLabelText('Desired timescale'), 'one-month')
    await user.click(screen.getByRole('button', { name: 'See my result' }))
    expect(screen.getByRole('heading', { name: /Emergency lighting testing is likely to be relevant/i })).toBeInTheDocument()
    expect(screen.getByText(/not a fire risk assessment, emergency-lighting test or legal decision/i)).toBeInTheDocument()
    expect(screen.getAllByText(/Evidence found/i)).toHaveLength(3)
    await user.click(screen.getByRole('button', { name: 'Continue with my project brief' }))
    expect(screen.getByRole('heading', { name: 'Who should we contact about this project?' })).toBeInTheDocument()
  })

  it('completes the LEV journey and shows an explainable result, price and shortlist', async () => {
    const user = userEvent.setup()
    render(<ServiceAssessmentWizard serviceId="lev" />)
    const first = screen.getByRole('button', { name: 'Continue' })
    expect(first).toBeDisabled()
    await user.selectOptions(screen.getByLabelText('Business or industry'), 'manufacturing')
    await user.click(screen.getByText('Welding or metal fume'))
    expect(first).toBeEnabled()
    await user.click(first)
    const second = screen.getByRole('button', { name: 'Continue' })
    await user.click(screen.getByText('On-tool extraction'))
    expect(second).toBeEnabled()
    await user.click(second)
    const resultButton = screen.getByRole('button', { name: 'See my result' })
    expect(resultButton).toBeDisabled()
    await user.selectOptions(screen.getByLabelText('Approximate site size'), 'small')
    await user.selectOptions(screen.getByLabelText('Commissioning data, logbook and previous reports'), 'partial')
    await user.selectOptions(screen.getByLabelText('Last thorough examination and test'), 'overdue-or-unknown')
    await user.selectOptions(screen.getByLabelText('Reason for commissioning'), 'first-examination')
    await user.selectOptions(screen.getByLabelText('Region'), 'midlands')
    await user.selectOptions(screen.getByLabelText('Desired timescale'), 'one-month')
    expect(resultButton).toBeEnabled()
    await user.click(resultButton)
    expect(screen.getByRole('heading', { name: /LEV testing is likely to be relevant/i })).toBeInTheDocument()
    expect(screen.getByText(/Deterministic Vendor Atlas estimate/i)).toBeInTheDocument()
    expect(screen.getAllByText(/Evidence found/i)).toHaveLength(3)
    await user.click(screen.getByRole('button', { name: 'Continue with my project brief' }))
    expect(screen.getByRole('heading', { name: 'Who should we contact about this project?' })).toBeInTheDocument()
  })

  it('requires an explicit duty-indicator answer and does not allow an accidental blank', async () => {
    const user = userEvent.setup()
    render(<ServiceAssessmentWizard serviceId="pressure-systems" />)
    await user.selectOptions(screen.getByLabelText('Business or industry'), 'manufacturing')
    await user.click(screen.getByText('Compressed-air system'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    const next = screen.getByRole('button', { name: 'Continue' })
    expect(next).toBeDisabled()
    await user.click(screen.getByText('Pressure or fluid details unknown'))
    expect(next).toBeEnabled()
  })

  it('completes the commercial EICR journey with a sourced price and provider shortlist', async () => {
    const user = userEvent.setup()
    render(<ServiceAssessmentWizard serviceId="commercial-eicr" />)
    await user.selectOptions(screen.getByLabelText('Business or industry'), 'manufacturing')
    await user.click(screen.getByText('Industrial or workshop installation'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.click(screen.getByText('Damage, fault or overheating is reported'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.selectOptions(screen.getByLabelText('Approximate site size'), 'small')
    await user.selectOptions(screen.getByLabelText('Circuit schedules, previous EICR and maintenance records'), 'partial')
    await user.selectOptions(screen.getByLabelText('Current fixed-wiring inspection position'), 'overdue-or-unknown')
    await user.selectOptions(screen.getByLabelText('Reason for commissioning'), 'first-examination')
    await user.selectOptions(screen.getByLabelText('Region'), 'midlands')
    await user.selectOptions(screen.getByLabelText('Desired timescale'), 'one-month')
    await user.click(screen.getByRole('button', { name: 'See my result' }))
    expect(screen.getByRole('heading', { name: /Commercial EICR is likely to be relevant/i })).toBeInTheDocument()
    expect(screen.getByText(/Two published provider tariff examples/i)).toBeInTheDocument()
    expect(screen.getAllByText(/Evidence found/i)).toHaveLength(3)
    await user.click(screen.getByRole('button', { name: 'Continue with my project brief' }))
    expect(screen.getByRole('heading', { name: 'Who should we contact about this project?' })).toBeInTheDocument()
  })

  it('completes the kitchen-extract journey and presents the source-limited price and shortlist', async () => {
    const user = userEvent.setup()
    render(<ServiceAssessmentWizard serviceId="kitchen-extract-cleaning" />)
    await user.selectOptions(screen.getByLabelText('Business or industry'), 'food-drink')
    await user.click(screen.getByText('One kitchen extract system'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.click(screen.getByText('The recorded clean is due or overdue'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.selectOptions(screen.getByLabelText('Approximate site size'), 'small')
    await user.selectOptions(screen.getByLabelText(/Cleaning reports, grease readings/), 'partial')
    await user.selectOptions(screen.getByLabelText('Current cleaning position'), 'overdue-or-unknown')
    await user.selectOptions(screen.getByLabelText('Reason for commissioning'), 'routine')
    await user.selectOptions(screen.getByLabelText('Region'), 'midlands')
    await user.selectOptions(screen.getByLabelText('Desired timescale'), 'one-month')
    await user.click(screen.getByRole('button', { name: 'See my result' }))
    expect(screen.getByRole('heading', { name: /A kitchen extract clean or review is likely to be relevant/i })).toBeInTheDocument()
    expect(screen.getByText(/Single-provider price example/i)).toBeInTheDocument()
    expect(screen.getAllByText(/£300–£500/).length).toBeGreaterThan(0)
    expect(screen.getByText(/VAT not stated/i)).toBeInTheDocument()
    expect(screen.getAllByText(/Evidence found/i)).toHaveLength(3)
    expect(screen.getByText(/not a national market range/i)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Continue with my project brief' }))
    expect(screen.getByRole('heading', { name: 'Who should we contact about this project?' })).toBeInTheDocument()
  })

  it('completes the first-aid training check through its sourced example and quote brief', async () => {
    const user = userEvent.setup()
    render(<ServiceAssessmentWizard serviceId="workplace-first-aid-training" />)
    await user.selectOptions(screen.getByLabelText('Business or industry'), 'manufacturing')
    await user.click(screen.getByRole('radio', { name: /Emergency First Aid at Work \(EFAW\)/ }))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.click(screen.getByRole('radio', { name: /identifies a course and training places to arrange/i }))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.selectOptions(screen.getByLabelText('Approximate site size'), 'small')
    await user.selectOptions(screen.getByLabelText('First-aid needs assessment and training records'), 'available')
    await user.selectOptions(screen.getByLabelText('Current certificate position for the people in scope'), 'in-date')
    await user.selectOptions(screen.getByLabelText('What is prompting the training plan?'), 'first-examination')
    await user.selectOptions(screen.getByLabelText('Region'), 'north')
    await user.selectOptions(screen.getByLabelText('Desired timescale'), 'one-month')
    await user.click(screen.getByRole('button', { name: 'See my result' }))

    expect(screen.getByRole('heading', { name: /needs assessment identifies EFAW training to arrange/i })).toBeInTheDocument()
    expect(screen.getByText(/Based on your employer’s existing needs assessment/i)).toBeInTheDocument()
    expect(screen.getAllByText('£450').length).toBeGreaterThan(0)
    expect(screen.getAllByText(/Evidence found/i)).toHaveLength(3)
    await user.click(screen.getByRole('button', { name: 'Continue with training quote brief' }))
    expect(screen.getByRole('heading', { name: 'Who should we contact about this project?' })).toBeInTheDocument()
    expect(screen.getByText(/selected course, learner count, location and timing/i)).toBeInTheDocument()
  })

  it('does not show a price, supplier matches or quote request without an employer decision', async () => {
    const user = userEvent.setup()
    render(<ServiceAssessmentWizard serviceId="workplace-first-aid-training" />)
    await user.selectOptions(screen.getByLabelText('Business or industry'), 'manufacturing')
    await user.click(screen.getByRole('radio', { name: /Not decided or not sure/i }))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.click(screen.getByRole('radio', { name: /does not currently identify a training course to buy/i }))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.selectOptions(screen.getByLabelText('Approximate site size'), 'small')
    await user.selectOptions(screen.getByLabelText('First-aid needs assessment and training records'), 'available')
    await user.selectOptions(screen.getByLabelText('Current certificate position for the people in scope'), 'in-date')
    await user.selectOptions(screen.getByLabelText('What is prompting the training plan?'), 'routine')
    await user.selectOptions(screen.getByLabelText('Region'), 'midlands')
    await user.selectOptions(screen.getByLabelText('Desired timescale'), 'planning')
    await user.click(screen.getByRole('button', { name: 'See my result' }))

    expect(screen.getByRole('heading', { name: 'Your assessment does not currently identify training to buy' })).toBeInTheDocument()
    expect(screen.queryByText('£450')).not.toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: /Providers with evidence/i })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Continue with training quote brief' })).not.toBeInTheDocument()
  })

  it('does not expose cleaning-price or quote actions when no grease-laden system is selected', async () => {
    const user = userEvent.setup()
    render(<ServiceAssessmentWizard serviceId="kitchen-extract-cleaning" />)
    await user.selectOptions(screen.getByLabelText('Business or industry'), 'food-drink')
    await user.click(screen.getByText('No grease-laden kitchen extract system'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.click(screen.getByText('The recorded clean is due or overdue'))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.selectOptions(screen.getByLabelText('Approximate site size'), 'small')
    await user.selectOptions(screen.getByLabelText(/Cleaning reports, grease readings/), 'available')
    await user.selectOptions(screen.getByLabelText('Current cleaning position'), 'in-date')
    await user.selectOptions(screen.getByLabelText('Reason for commissioning'), 'routine')
    await user.selectOptions(screen.getByLabelText('Region'), 'midlands')
    await user.selectOptions(screen.getByLabelText('Desired timescale'), 'one-month')
    await user.click(screen.getByRole('button', { name: 'See my result' }))
    expect(screen.getByRole('heading', { name: 'No grease-laden kitchen extract system was identified' })).toBeInTheDocument()
    expect(screen.queryByText(/£300–£500/)).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Continue with my project brief' })).not.toBeInTheDocument()
    expect(screen.getByText(/This finder is only for cleaning an installed grease-laden kitchen extract system/i)).toBeInTheDocument()
  })
})
