import type {
  PriceEstimate,
  QualificationResult,
  ServiceAssessmentAnswers,
  ServiceId,
} from './types'

type IndustrialServiceId = Exclude<ServiceId, 'dsear'>

export interface AssessmentOption {
  value: string
  label: string
  detail: string
}

export interface ServiceDefinition {
  id: IndustrialServiceId
  name: string
  shortName: string
  eyebrow: string
  question: string
  promise: string
  description: string
  legalBasis: string
  legalSource: string
  guidePath: string
  costPath: string
  supplierPath: string
  toolkitPath: string
  workHeading: string
  workHelp: string
  workOptions: AssessmentOption[]
  signalHeading: string
  signalHelp: string
  signalOptions: AssessmentOption[]
  assetLabel: string
  secondaryLabel: string
  documentationLabel: string
  documentationOptions: Array<{ value: ServiceAssessmentAnswers['documentationStatus']; label: string }>
  inspectionLabel: string
  inspectionOptions: Array<{ value: ServiceAssessmentAnswers['inspectionStatus']; label: string }>
  resultResourceHeading: string
  resultResourceBody: string
  primaryLinks: Array<{ label: string; detail: string; url: string }>
  priceEvidence: Array<{ label: string; url: string; note: string }>
}

const sharedDocumentation = [
  { value: 'none', label: 'No useful records found' },
  { value: 'partial', label: 'Some records, but incomplete' },
  { value: 'available', label: 'Current records are available' },
  { value: 'unknown', label: 'Not sure what records exist' },
] as ServiceDefinition['documentationOptions']

export const serviceDefinitions: Record<IndustrialServiceId, ServiceDefinition> = {
  lev: {
    id: 'lev',
    name: 'Local exhaust ventilation thorough examination and test',
    shortName: 'LEV testing',
    eyebrow: 'LEV examination finder',
    question: 'Does my extraction system need an LEV test?',
    promise: 'Build an initial answer and a comparable testing brief in about 2 minutes.',
    description: 'Check likely COSHH examination duties, understand what a proper TExT should include, estimate a planning range and compare evidenced UK specialists.',
    legalBasis: 'COSHH regulation 9 requires control measures to be maintained. Most LEV systems must be thoroughly examined and tested at least every 14 months, with shorter maximum intervals for specified processes.',
    legalSource: 'https://www.hse.gov.uk/lev/faqs.htm',
    guidePath: '/lev/do-i-need-an-lev-test',
    costPath: '/lev/cost',
    supplierPath: '/lev/suppliers',
    toolkitPath: '/lev/buying-toolkit',
    workHeading: 'What airborne contaminant does the system control?',
    workHelp: 'Include contaminants generated by the process, not only substances bought in. Choose every relevant type.',
    workOptions: [
      { value: 'wood-dust', label: 'Wood dust', detail: 'Sawing, sanding, routing or machining timber and boards' },
      { value: 'welding-fume', label: 'Welding or metal fume', detail: 'Welding, soldering, brazing, plasma cutting or thermal work' },
      { value: 'spray-mist', label: 'Spray mist or coating', detail: 'Paint, powder coating, adhesives or other sprayed products' },
      { value: 'stone-dust', label: 'Stone, silica or construction dust', detail: 'Cutting, grinding or shaping mineral materials' },
      { value: 'metal-dust', label: 'Metal dust', detail: 'Grinding, polishing, finishing or additive manufacture' },
      { value: 'solvent-vapour', label: 'Solvent or chemical vapour', detail: 'Vapours released from a process, bath, vessel or cleaning activity' },
      { value: 'laboratory-fume', label: 'Laboratory or pharmaceutical contaminant', detail: 'Fume cupboards, microbiological cabinets or contained process work' },
      { value: 'other-contaminant', label: 'Other airborne contaminant', detail: 'Another dust, fume, mist, smoke, gas or vapour' },
      { value: 'none-known', label: 'No contaminant identified', detail: 'Use only if the equipment is general ventilation rather than source capture' },
    ],
    signalHeading: 'What kind of extraction is involved?',
    signalHelp: 'A system can still be LEV when it is small, portable or fitted directly to a tool.',
    signalOptions: [
      { value: 'fixed-ducted', label: 'Fixed ducted system', detail: 'One or more hoods connected to ductwork, a fan and discharge or filter' },
      { value: 'on-tool', label: 'On-tool extraction', detail: 'Extraction integrated with or attached to a power tool' },
      { value: 'spray-booth', label: 'Spray booth or room', detail: 'Mechanical extraction controlling spray, mist or vapour' },
      { value: 'fume-cupboard', label: 'Fume cupboard or cabinet', detail: 'Laboratory, pharmaceutical or containment equipment' },
      { value: 'portable', label: 'Portable extraction unit', detail: 'A movable fume, dust or filtration unit' },
      { value: 'recirculating', label: 'Air is recirculated', detail: 'Filtered air is discharged back into the workplace' },
      { value: 'unknown-system', label: 'Not sure', detail: 'The equipment captures contaminant, but its configuration is unclear' },
    ],
    assetLabel: 'Number of LEV systems',
    secondaryLabel: 'Total hoods or extraction points',
    documentationLabel: 'Commissioning data, logbook and previous reports',
    documentationOptions: sharedDocumentation,
    inspectionLabel: 'Last thorough examination and test',
    inspectionOptions: [
      { value: 'none', label: 'Never tested' },
      { value: 'in-date', label: 'Tested within its stated interval' },
      { value: 'overdue-or-unknown', label: 'Overdue or date unknown' },
      { value: 'new-system', label: 'New or newly installed system' },
    ],
    resultResourceHeading: 'A TExT is different from routine servicing',
    resultResourceBody: 'HSE describes a three-stage check: physical examination, technical performance measurements and professional judgement about whether the system is controlling exposure. Repairs and servicing may be needed, but do not by themselves replace that examination.',
    primaryLinks: [
      { label: 'HSE LEV FAQs', detail: 'Duty, intervals and practical employer questions', url: 'https://www.hse.gov.uk/lev/faqs.htm' },
      { label: 'HSE HSG258', detail: 'Detailed design, testing and report guidance', url: 'https://books.hse.gov.uk/gempdf/hsg258.pdf' },
      { label: 'COSHH regulation 9', detail: 'Legal maintenance and examination requirement', url: 'https://www.legislation.gov.uk/uksi/2002/2677/regulation/9' },
    ],
    priceEvidence: [
      { label: 'Tim Prestage Ltd', url: 'https://timprestage.co.uk/lev-testing-and-certification/', note: 'Publishes approximately £200 plus VAT for one system with up to five extraction points.' },
      { label: 'Impact Technical Services', url: 'https://www.impacttechnicalservices.co.uk/services/lev-testing/', note: 'Publishes a starting point of £250 for a smaller single-point system.' },
      { label: 'Spray Direct', url: 'https://www.spraydirect.co.uk/acatalog/Spray-Booth-Local-Exhaust-Ventilation-Testing-LEV.html', note: 'Publishes £245 ex VAT per spray-booth fan at the checked date.' },
    ],
  },
  'pressure-systems': {
    id: 'pressure-systems',
    name: 'Pressure systems written scheme and examination',
    shortName: 'Pressure systems / PSSR',
    eyebrow: 'Pressure-system duty finder',
    question: 'Does my pressure system need a written scheme?',
    promise: 'Identify the obvious PSSR signals and build a competent-person brief in about 2 minutes.',
    description: 'Check likely PSSR relevance, understand the written-scheme and examination sequence, estimate a planning range and compare evidenced UK providers.',
    legalBasis: 'Before qualifying pressure equipment is used, a suitable written scheme of examination must be in place and the covered parts must be examined by a competent person in accordance with it.',
    legalSource: 'https://www.hse.gov.uk/pressure-systems/pssr.htm',
    guidePath: '/pressure-systems/do-i-need-a-written-scheme',
    costPath: '/pressure-systems/cost',
    supplierPath: '/pressure-systems/suppliers',
    toolkitPath: '/pressure-systems/buying-toolkit',
    workHeading: 'What pressure equipment is present?',
    workHelp: 'Choose equipment that belongs to the system, including vessels, associated pipework and protective devices where relevant.',
    workOptions: [
      { value: 'compressed-air', label: 'Compressed-air system', detail: 'Compressor, receiver, dryer, pipework and protective devices' },
      { value: 'steam-boiler', label: 'Steam boiler or steam system', detail: 'Steam at any pressure can be a relevant fluid under PSSR' },
      { value: 'refrigeration', label: 'Refrigeration or HVAC pressure plant', detail: 'Systems containing compressed or liquefied refrigerant' },
      { value: 'autoclave', label: 'Autoclave or steriliser', detail: 'A pressurised vessel used in healthcare, laboratory or manufacturing work' },
      { value: 'hot-water', label: 'Pressurised hot-water system', detail: 'Especially water kept above 110°C' },
      { value: 'process-vessel', label: 'Industrial process vessel', detail: 'Reactor, accumulator, heat exchanger or another pressure vessel' },
      { value: 'coffee-boiler', label: 'Commercial coffee boiler', detail: 'An espresso or beverage machine producing steam' },
      { value: 'gas-system', label: 'Compressed or liquefied gas system', detail: 'Gas vessel, associated pipework and protective devices' },
      { value: 'unknown-pressure', label: 'Other or uncertain pressure system', detail: 'The system stores pressure but its classification is unclear' },
    ],
    signalHeading: 'Which relevant-fluid indicators apply?',
    signalHelp: 'The exact system boundary and exclusions require competent review. These answers are only the initial screen.',
    signalOptions: [
      { value: 'steam', label: 'Steam at any pressure', detail: 'Includes fired or electrically heated steam equipment' },
      { value: 'gas-over-half-bar', label: 'Gas above 0.5 bar', detail: 'Compressed or liquefied gas, including air, above atmospheric pressure' },
      { value: 'hot-water-over-110', label: 'Pressurised water above 110°C', detail: 'High-temperature water capable of generating relevant vapour pressure' },
      { value: 'acetylene', label: 'Gas dissolved under pressure', detail: 'For example acetylene dissolved in a solvent' },
      { value: 'unknown-fluid', label: 'Pressure or fluid details unknown', detail: 'Treat missing design information as a scoping gap' },
      { value: 'no-relevant-fluid', label: 'None of these', detail: 'Use only after checking the operating pressure, temperature and fluid' },
    ],
    assetLabel: 'Number of pressure vessels or main plant items',
    secondaryLabel: 'Protective devices to be identified',
    documentationLabel: 'System drawings, safe limits and equipment records',
    documentationOptions: sharedDocumentation,
    inspectionLabel: 'Written scheme and current examination position',
    inspectionOptions: [
      { value: 'none', label: 'No written scheme or examination found' },
      { value: 'in-date', label: 'Written scheme and examinations believed current' },
      { value: 'overdue-or-unknown', label: 'Scheme exists but status is overdue or unclear' },
      { value: 'new-system', label: 'New system, not yet put into service' },
    ],
    resultResourceHeading: 'The scheme comes before the examination',
    resultResourceBody: 'The written scheme identifies the safety-critical parts, nature of examinations, preparation measures and maximum intervals. The examination then follows that system-specific scheme. Neither replaces routine operation, maintenance or safe-limit information.',
    primaryLinks: [
      { label: 'HSE PSSR overview', detail: 'Definitions, relevant fluids and competent-person role', url: 'https://www.hse.gov.uk/pressure-systems/pssr.htm' },
      { label: 'HSE written-scheme guide', detail: 'How to establish and review a suitable WSE', url: 'https://www.hse.gov.uk/pubns/indg178.htm' },
      { label: 'PSSR regulation 8', detail: 'Legal requirement for a written scheme', url: 'https://www.legislation.gov.uk/uksi/2000/128/regulation/8' },
    ],
    priceEvidence: [
      { label: 'Lloyd & Whyte', url: 'https://www.lloydwhyte.com/commercial-insurance/pressure-vessel-inspection/', note: 'Publishes £255 plus VAT and an administration fee for its specified pressure-vessel inspection service.' },
      { label: 'Bridge Coffee Roasters', url: 'https://bridgecoffeeroasters.co.uk/boilerinspections', note: 'Publishes £445 per coffee machine including its stated inspection, certification, records and standard parts.' },
      { label: 'United Coffee Company', url: 'https://www.united-coffee.co.uk/machines/statutory-pressure-testing/', note: 'Publishes a single-machine pressure-vessel test from £318.75 plus VAT.' },
    ],
  },
  loler: {
    id: 'loler',
    name: 'LOLER thorough examination',
    shortName: 'LOLER examinations',
    eyebrow: 'Lifting-equipment examination finder',
    question: 'Which lifting equipment needs a thorough examination?',
    promise: 'Turn an initial asset count into a defensible examination and quote brief in about 2 minutes.',
    description: 'Check likely LOLER relevance, understand normal examination intervals, estimate an asset-based planning range and compare evidenced UK providers.',
    legalBasis: 'LOLER requires systematic and detailed thorough examination by a competent person at specified points and intervals, with a written report and action on defects.',
    legalSource: 'https://www.hse.gov.uk/work-equipment-machinery/thorough-examinations-lifting-equipment.htm',
    guidePath: '/loler/does-loler-apply',
    costPath: '/loler/cost',
    supplierPath: '/loler/suppliers',
    toolkitPath: '/loler/buying-toolkit',
    workHeading: 'What lifting equipment or accessories are involved?',
    workHelp: 'Choose every relevant group. A provider will still need an itemised asset register before confirming a quote.',
    workOptions: [
      { value: 'passenger-lift', label: 'Passenger, platform or mobility lift', detail: 'Equipment intended to lift people within or around a building' },
      { value: 'goods-lift', label: 'Goods lift or hoist', detail: 'Fixed equipment lifting goods rather than people' },
      { value: 'forklift', label: 'Forklift, telehandler or attachment', detail: 'Materials-handling plant and lifting attachments' },
      { value: 'mewp', label: 'MEWP or access platform', detail: 'Mobile equipment used to raise people to a working position' },
      { value: 'crane-hoist', label: 'Crane, runway, beam or powered hoist', detail: 'Fixed, mobile or overhead lifting machinery' },
      { value: 'vehicle-lift', label: 'Vehicle lift, jack or workshop equipment', detail: 'Garage and maintenance lifting equipment' },
      { value: 'patient-hoist', label: 'Patient hoist or care equipment', detail: 'Equipment and accessories used to lift or support people' },
      { value: 'accessories', label: 'Slings, chains, shackles or accessories', detail: 'Items used to attach a load to lifting equipment' },
      { value: 'arborist-kit', label: 'Arborist climbing or rigging kit', detail: 'Ropes, harnesses, connectors and rigging equipment' },
      { value: 'unknown-lifting', label: 'Other or uncertain lifting equipment', detail: 'The item raises or lowers a load, but classification is unclear' },
    ],
    signalHeading: 'How is it used?',
    signalHelp: 'This affects the usual maximum interval and the competence needed for the equipment type.',
    signalOptions: [
      { value: 'lifts-people', label: 'Lifts people', detail: 'Normally points to a six-month maximum interval unless a scheme specifies otherwise' },
      { value: 'lifts-loads', label: 'Lifts goods or loads', detail: 'Other lifting equipment commonly has a 12-month maximum interval' },
      { value: 'lifting-accessory', label: 'Includes lifting accessories', detail: 'Accessories commonly have a six-month maximum interval' },
      { value: 'assembled-on-site', label: 'Assembled or installed at a location', detail: 'May need examination after assembly and before use' },
      { value: 'exceptional-event', label: 'Damage, major repair, relocation or long disuse', detail: 'Exceptional circumstances may trigger another examination' },
      { value: 'unknown-use', label: 'Use is uncertain', detail: 'The asset needs classification before an interval is assumed' },
    ],
    assetLabel: 'Main items of lifting equipment',
    secondaryLabel: 'Lifting accessories',
    documentationLabel: 'Asset register, declarations and previous reports',
    documentationOptions: sharedDocumentation,
    inspectionLabel: 'Current thorough-examination position',
    inspectionOptions: [
      { value: 'none', label: 'No examination records found' },
      { value: 'in-date', label: 'Reports believed current' },
      { value: 'overdue-or-unknown', label: 'Overdue or due dates unknown' },
      { value: 'new-system', label: 'New, relocated or newly assembled equipment' },
    ],
    resultResourceHeading: 'Thorough examination is not routine servicing',
    resultResourceBody: 'A competent person examines safety-critical parts, makes judgements about defects and issues the legally required report. Maintenance under PUWER remains separate. HSE advises that the examiner should have sufficient independence and should not simply assess their own maintenance work.',
    primaryLinks: [
      { label: 'HSE thorough-examination guide', detail: 'Triggers, intervals, reports and defect duties', url: 'https://www.hse.gov.uk/work-equipment-machinery/thorough-examinations-lifting-equipment.htm' },
      { label: 'HSE LOLER overview', detail: 'Scope and dutyholder introduction', url: 'https://www.hse.gov.uk/work-equipment-machinery/loler-overview.htm' },
      { label: 'LOLER regulation 9', detail: 'Legal thorough-examination requirements', url: 'https://www.legislation.gov.uk/uksi/1998/2307/regulation/9' },
    ],
    priceEvidence: [
      { label: 'Robinsons Facilities Services', url: 'https://www.robinsonsfs.com/services/lifting-and-hoisting-equipment/', note: 'Publishes examinations from £150 plus VAT per item and a £180 minimum visit charge.' },
      { label: 'The LOLER Man', url: 'https://thelolerman.co.uk/', note: 'Publishes £80 for small equipment and £115 for plant, with travel excluded.' },
      { label: 'LOLER for Arborists', url: 'https://www.lolerforarborists.co.uk/pricing', note: 'Publishes £75 for an initial kit examination and £65 for re-examination within its stated kit limits.' },
    ],
  },
  asbestos: {
    id: 'asbestos',
    name: 'asbestos survey and register support',
    shortName: 'Asbestos surveys',
    eyebrow: 'Asbestos survey finder',
    question: 'Which asbestos survey does my building need?',
    promise: 'Check the likely duty, survey type and quote scope in about 2 minutes.',
    description: 'Screen the obvious duty-to-manage and planned-work signals, see what a suitable survey should cover, estimate a transparent planning range and compare evidenced UK providers.',
    legalBasis: 'Regulation 4 of the Control of Asbestos Regulations 2012 places duties on those responsible for maintenance of non-domestic premises. The duty includes finding materials that may contain asbestos, assessing condition and managing the risk.',
    legalSource: 'https://www.hse.gov.uk/asbestos/duty/index.htm',
    guidePath: '/asbestos/do-i-need-an-asbestos-survey',
    costPath: '/asbestos/cost',
    supplierPath: '/asbestos/suppliers',
    toolkitPath: '/asbestos/buying-toolkit',
    workHeading: 'What premises or work are involved?',
    workHelp: 'Choose every relevant situation. A management survey and an intrusive refurbishment or demolition survey answer different questions.',
    workOptions: [
      { value: 'occupied-non-domestic', label: 'Occupied non-domestic premises', detail: 'Workplace, shop, office, factory, school, warehouse or other commercial building' },
      { value: 'common-parts', label: 'Common parts of domestic premises', detail: 'Shared corridors, plant rooms, lifts, roofs or service areas' },
      { value: 'maintenance-work', label: 'Routine maintenance is planned', detail: 'Work may reach concealed building fabric or services' },
      { value: 'refurbishment', label: 'Refurbishment or alteration', detail: 'Intrusive work will disturb part of the building' },
      { value: 'demolition', label: 'Demolition', detail: 'All or a substantial part of the structure will be removed' },
      { value: 'property-acquisition', label: 'Acquisition or lease review', detail: 'The buyer or tenant needs dependable building-risk information' },
      { value: 'unknown-use', label: 'Premises or work scope uncertain', detail: 'The dutyholder, building use or planned work is not yet clear' },
    ],
    signalHeading: 'Which asbestos risk signals apply?',
    signalHelp: 'Buildings constructed before 2000 may contain asbestos. Records and planned disturbance materially affect the survey brief.',
    signalOptions: [
      { value: 'built-before-2000', label: 'Built before 2000', detail: 'Asbestos-containing materials may be present' },
      { value: 'suspect-material', label: 'Suspect material is present', detail: 'Material has not been reliably identified' },
      { value: 'no-register', label: 'No usable asbestos register', detail: 'The live location and condition record is missing or incomplete' },
      { value: 'planned-disturbance', label: 'Work will disturb building fabric', detail: 'Refurbishment, installation or demolition reaches the work area' },
      { value: 'damaged-material', label: 'Material is damaged or deteriorating', detail: 'Condition may need prompt competent review' },
      { value: 'previous-findings', label: 'Previous asbestos findings', detail: 'A survey or sample has identified asbestos-containing material' },
      { value: 'unknown-building-age', label: 'Building age is unknown', detail: 'Construction information needs checking before exclusion' },
      { value: 'post-2000-evidence', label: 'Reliable post-2000 construction evidence', detail: 'Records indicate the relevant structure was built after asbestos use was prohibited' },
    ],
    assetLabel: 'Buildings or separate blocks in scope',
    secondaryLabel: 'Expected samples or suspect material locations',
    documentationLabel: 'Existing survey, register and management plan',
    documentationOptions: sharedDocumentation,
    inspectionLabel: 'Current survey and reinspection position',
    inspectionOptions: [
      { value: 'none', label: 'No survey or register found' },
      { value: 'in-date', label: 'Survey, register and reviews believed current' },
      { value: 'overdue-or-unknown', label: 'Records exist but status is unclear or overdue' },
      { value: 'new-system', label: 'New premises or newly planned work' },
    ],
    resultResourceHeading: 'Choose the survey for the decision being made',
    resultResourceBody: 'A management survey supports normal occupation and routine maintenance. Refurbishment or demolition work needs a more intrusive survey of the parts that will be disturbed. The survey brief should define areas, access, exclusions, sampling and the format needed for the live register or project controls.',
    primaryLinks: [
      { label: 'HSE asbestos duty', detail: 'Who has the duty to manage and what it involves', url: 'https://www.hse.gov.uk/asbestos/duty/index.htm' },
      { label: 'HSE survey guide', detail: 'Survey types, planning and choosing a surveyor', url: 'https://www.hse.gov.uk/asbestos/duty/arrange-asbestos-survey.htm' },
      { label: 'Control of Asbestos Regulations 2012', detail: 'Regulation 4 duty to manage asbestos', url: 'https://www.legislation.gov.uk/uksi/2012/632/regulation/4' },
    ],
    priceEvidence: [
      { label: 'ACMS UK', url: 'https://www.acmsuk.com/news/asbestos/asbestos-survey-cost/', note: 'Publishes commercial management-survey examples and explains major price drivers.' },
      { label: 'Elements Environmental', url: 'https://www.asbestossurveyingandtesting.com/knowledge-centre/guides/management-surveys', note: 'Publishes size-banded commercial management-survey guidance.' },
      { label: 'Supernova Asbestos Surveys', url: 'https://asbestos-surveys.org.uk/services', note: 'Publishes starting prices for management, refurbishment, demolition and reinspection work.' },
    ],
  },
  'fire-risk-assessment': {
    id: 'fire-risk-assessment',
    name: 'fire risk assessment',
    shortName: 'Fire risk assessments',
    eyebrow: 'Fire risk assessment finder',
    question: 'Does my premises need a fire risk assessment?',
    promise: 'Check the likely duty, assessment scope and quote inputs in about 2 minutes.',
    description: 'Identify the responsible-person and premises signals, see what a suitable assessment should cover, estimate a visible planning range and compare sourced providers.',
    legalBasis: 'In England and Wales, the Regulatory Reform (Fire Safety) Order 2005 requires the responsible person to make a suitable and sufficient assessment of risks to relevant persons and keep it under review. Different legislation applies in Scotland and Northern Ireland.',
    legalSource: 'https://www.gov.uk/workplace-fire-safety-your-responsibilities/fire-risk-assessments',
    guidePath: '/fire-risk-assessment/do-i-need-a-fire-risk-assessment',
    costPath: '/fire-risk-assessment/cost',
    supplierPath: '/fire-risk-assessment/suppliers',
    toolkitPath: '/fire-risk-assessment/buying-toolkit',
    workHeading: 'What type of premises is involved?',
    workHelp: 'Choose every relevant use. Mixed and shared premises can have more than one responsible person.',
    workOptions: [
      { value: 'office-retail', label: 'Office, shop or salon', detail: 'Non-domestic workplace or premises open to customers' },
      { value: 'factory-warehouse', label: 'Factory or warehouse', detail: 'Industrial, storage or distribution premises' },
      { value: 'hospitality', label: 'Restaurant, pub or venue', detail: 'Cooking, alcohol, public assembly or entertainment use' },
      { value: 'sleeping-accommodation', label: 'Hotel, guest accommodation or HMO', detail: 'People sleep at the premises and may be unfamiliar with escape routes' },
      { value: 'residential-common-parts', label: 'Block of flats common parts', detail: 'Shared areas, structure, external walls and flat entrance doors may need consideration' },
      { value: 'care-education', label: 'Care, healthcare or education', detail: 'Children, patients or people needing assistance may be present' },
      { value: 'construction-site', label: 'Construction or refurbishment site', detail: 'Temporary conditions, hot work and changing escape routes apply' },
      { value: 'mixed-use', label: 'Mixed-use or multi-occupied building', detail: 'Several uses, occupiers or responsible persons share the premises' },
      { value: 'none-private-home', label: 'Private home only', detail: 'A single private domestic dwelling with no business, paying guests or shared common parts' },
      { value: 'unknown-premises', label: 'Premises use is uncertain', detail: 'Ownership, occupation or fire-safety responsibility needs checking' },
    ],
    signalHeading: 'Which fire-safety scope signals apply?',
    signalHelp: 'These factors affect assessment depth, assessor competence and quotation effort. They do not determine the assessment outcome.',
    signalOptions: [
      { value: 'employees-public', label: 'Employees, customers or visitors attend', detail: 'Relevant persons use or may be near the premises' },
      { value: 'sleeping-risk', label: 'People sleep at the premises', detail: 'Sleeping risk changes evacuation and detection considerations' },
      { value: 'vulnerable-occupants', label: 'People may need assistance to escape', detail: 'Children, patients, residents or disabled people need suitable planning' },
      { value: 'dangerous-substances', label: 'Dangerous substances or higher fire load', detail: 'Fuel, gases, chemicals, combustible stock or process hazards are present' },
      { value: 'multiple-floors', label: 'Several floors or complex escape routes', detail: 'Travel distances, stairs, compartmentation and evacuation need closer review' },
      { value: 'shared-responsibility', label: 'Several occupiers or dutyholders', detail: 'Co-operation and co-ordination arrangements need assessment' },
      { value: 'material-change', label: 'Change, fire or near miss', detail: 'A change or event can trigger review of an existing assessment' },
      { value: 'unknown-fire-scope', label: 'Fire-safety information is incomplete', detail: 'Plans, occupancy, systems or previous findings need checking' },
      { value: 'no-complex-signals', label: 'None of these complexity signals', detail: 'The premises still needs its legal duty and assessment position checked' },
    ],
    assetLabel: 'Floors or distinct levels in scope',
    secondaryLabel: 'Separate occupancies or tenant areas',
    documentationLabel: 'Existing assessment, plans and fire-safety records',
    documentationOptions: sharedDocumentation,
    inspectionLabel: 'Current fire risk assessment position',
    inspectionOptions: [
      { value: 'none', label: 'No written assessment found' },
      { value: 'in-date', label: 'Assessment is recorded and believed current' },
      { value: 'overdue-or-unknown', label: 'Assessment exists but review status is unclear' },
      { value: 'new-system', label: 'New premises, use or occupancy' },
    ],
    resultResourceHeading: 'The responsible person owns the duty',
    resultResourceBody: 'A responsible person can carry out a straightforward assessment if competent, or appoint a competent assessor. Outsourcing the work does not transfer the legal responsibility. The brief should describe the premises, people, hazards, fire precautions, records, shared responsibilities and intended report.',
    primaryLinks: [
      { label: 'GOV.UK fire risk assessments', detail: 'Responsible-person duty and five assessment steps', url: 'https://www.gov.uk/workplace-fire-safety-your-responsibilities/fire-risk-assessments' },
      { label: 'Home Office five-step checklist', detail: 'Hazards, people, action, records and review', url: 'https://www.gov.uk/government/publications/fire-safety-risk-assessment-5-step-checklist/fire-safety-risk-assessment-5-step-checklist-accessible' },
      { label: 'Fire Safety Order article 9', detail: 'Legal risk-assessment and review requirement', url: 'https://www.legislation.gov.uk/uksi/2005/1541/article/9' },
    ],
    priceEvidence: [
      { label: 'R&W Fire Solutions', url: 'https://www.rwfiresolutions.com/fire-risk-assessments', note: 'Publishes starting prices of £250 for small, £450 for medium and £750 for large or complex premises.' },
      { label: 'MG Fire Safety Group', url: 'https://www.londonfireriskassessment.com/pricing/pricing', note: 'Publishes commercial-premises prices by stated floor-area band.' },
      { label: 'Landlord Compliance London', url: 'https://landlordcompliancelondon.uk/services/commercial-fire-risk-assessment', note: 'Publishes prices by floor count for communal areas and full buildings.' },
    ],
  },
  legionella: {
    id: 'legionella',
    name: 'legionella risk assessment',
    shortName: 'Legionella risk assessments',
    eyebrow: 'Legionella duty finder',
    question: 'Does my water system need a legionella risk assessment?',
    promise: 'Check the duty, water-system scope and quote inputs in about 2 minutes.',
    description: 'Identify the water-system and exposed-person signals, see what an assessment should cover, calculate a visible planning range and compare sourced UK providers.',
    legalBasis: 'UK employers and people in control of premises must assess and control legionella exposure risks under health and safety law and COSHH. HSE ACOP L8 explains how those duties apply to water systems.',
    legalSource: 'https://www.hse.gov.uk/pubns/priced/l8.pdf',
    guidePath: '/legionella/do-i-need-a-legionella-risk-assessment',
    costPath: '/legionella/cost',
    supplierPath: '/legionella/suppliers',
    toolkitPath: '/legionella/buying-toolkit',
    workHeading: 'Which water systems or premises are involved?',
    workHelp: 'Choose every relevant system or use. The assessment must cover the real water assets and people who can be exposed.',
    workOptions: [
      { value: 'commercial-hot-cold', label: 'Commercial hot and cold water', detail: 'Offices, shops, factories, warehouses or public buildings' },
      { value: 'rented-housing', label: 'Rented housing or HMO', detail: 'A landlord or managing agent controls the domestic water system' },
      { value: 'care-healthcare', label: 'Care or healthcare premises', detail: 'Residents or patients can have greater susceptibility' },
      { value: 'hotel-hospitality', label: 'Hotel, hospitality or guest accommodation', detail: 'Bedrooms, showers and variable occupancy increase the asset count' },
      { value: 'leisure-spa', label: 'Leisure, pool or spa system', detail: 'Spa pools and wet leisure systems need specialist assessment' },
      { value: 'cooling-system', label: 'Cooling tower or evaporative condenser', detail: 'An evaporative cooling system has a separate HSG274 control route' },
      { value: 'process-water', label: 'Other risk water system', detail: 'Vehicle wash, humidifier, misting, dental, industrial or process system' },
      { value: 'none-no-water-system', label: 'No water system under our control', detail: 'Use only after confirming no premises or work activity creates exposure responsibility' },
      { value: 'unknown-water-system', label: 'Water system is uncertain', detail: 'Ownership, assets or system layout needs checking' },
    ],
    signalHeading: 'Which water-risk signals apply?',
    signalHelp: 'These factors affect the risk assessment depth and provider competence. They do not mean legionella is present.',
    signalOptions: [
      { value: 'stored-hot-water', label: 'Stored hot water or calorifiers', detail: 'Water is heated and stored rather than produced only at the outlet' },
      { value: 'cold-water-storage', label: 'Cold-water storage tanks', detail: 'Stored water condition, turnover and temperature need assessment' },
      { value: 'recirculation', label: 'Recirculating hot-water system', detail: 'Flow, return, temperature and balance affect control' },
      { value: 'showers-spray', label: 'Showers or aerosol-producing outlets', detail: 'Spray can create an exposure route if the system is contaminated' },
      { value: 'vulnerable-users', label: 'People with increased susceptibility', detail: 'Age, illness or reduced immunity changes consequence and control needs' },
      { value: 'little-used-outlets', label: 'Little-used outlets or vacant areas', detail: 'Low turnover and stagnation need to be identified' },
      { value: 'temperature-concerns', label: 'Temperature or control concerns', detail: 'Monitoring indicates control targets are missed or uncertain' },
      { value: 'previous-positive', label: 'Previous positive sample or case concern', detail: 'Investigation and specialist control review may be required' },
      { value: 'unknown-controls', label: 'Controls and records are uncertain', detail: 'Responsibility, monitoring or the written scheme needs checking' },
      { value: 'no-complex-water-signals', label: 'None of these complexity signals', detail: 'A simple system still needs a suitable dutyholder assessment' },
    ],
    assetLabel: 'Water outlets in scope',
    secondaryLabel: 'Tanks, calorifiers or other main assets',
    documentationLabel: 'Existing assessment, schematic and control records',
    documentationOptions: sharedDocumentation,
    inspectionLabel: 'Current risk-assessment position',
    inspectionOptions: [
      { value: 'none', label: 'No assessment found' },
      { value: 'in-date', label: 'Assessment is recorded and believed current' },
      { value: 'overdue-or-unknown', label: 'Assessment exists but review status is unclear' },
      { value: 'new-system', label: 'New premises or water system' },
    ],
    resultResourceHeading: 'Assessment comes before the control programme',
    resultResourceBody: 'The assessment identifies the system, sources of risk, people exposed and controls required. Its findings should drive a written scheme with responsibilities, monitoring, maintenance and review. Routine sampling is not an automatic substitute for assessing and controlling the system.',
    primaryLinks: [
      { label: 'HSE ACOP L8', detail: 'Legal duties, risk assessment and control principles', url: 'https://www.hse.gov.uk/pubns/priced/l8.pdf' },
      { label: 'HSE HSG274', detail: 'Technical guidance for cooling, hot and cold, and other water systems', url: 'https://www.hse.gov.uk/pubns/books/hsg274.htm' },
      { label: 'HSE employer responsibilities', detail: 'Practical dutyholder steps and competence', url: 'https://www.hse.gov.uk/legionnaires/employers-responsibilities.htm' },
    ],
    priceEvidence: [
      { label: 'Birmingham Water Solutions', url: 'https://birminghamwatersolutions.com/pages/resources/legionella-risk-assessment-cost', note: 'Publishes £250 to £450 for a stated small low-complexity building and higher bands for larger systems.' },
      { label: 'Aqua Legion UK', url: 'https://www.aqualegion.com/', note: 'Publishes set-price packages from £295 plus VAT based on location, complexity and time.' },
      { label: 'uRisk', url: 'https://www.urisk.co.uk/how-much-does-a-legionella-risk-assessment-cost/', note: 'Publishes commercial assessments from £300 plus VAT and a stated range for larger or more complex sites.' },
    ],
  },
  'pat-testing': {
    id: 'pat-testing',
    name: 'portable electrical equipment inspection and testing',
    shortName: 'PAT and electrical equipment checks',
    eyebrow: 'Electrical equipment maintenance finder',
    question: 'Does my workplace equipment need PAT testing?',
    promise: 'Check whether testing fits the maintenance risk in about 2 minutes.',
    description: 'Separate the legal maintenance duty from the annual-PAT myth, estimate a visible inspection and testing range, and compare sourced UK providers.',
    legalBasis: 'The Electricity at Work Regulations 1989 require electrical equipment that may cause danger to be maintained so far as is reasonably practicable. They do not prescribe annual PAT testing. Inspection and test frequency should follow equipment type, use and environment.',
    legalSource: 'https://www.hse.gov.uk/electricity/faq-portable-appliance-testing.htm',
    guidePath: '/pat-testing/do-i-need-pat-testing',
    costPath: '/pat-testing/cost',
    supplierPath: '/pat-testing/suppliers',
    toolkitPath: '/pat-testing/buying-toolkit',
    workHeading: 'Which electrical equipment is under your control?',
    workHelp: 'Include movable, portable, stationary and fixed equipment supplied for work. A plug is not the legal boundary.',
    workOptions: [
      { value: 'office-it', label: 'Office and IT equipment', detail: 'Computers, monitors, chargers, printers, kettles and extension leads' },
      { value: 'hospitality-kitchen', label: 'Hospitality or kitchen equipment', detail: 'Portable and stationary appliances used by staff or guests' },
      { value: 'tools-construction', label: 'Tools or construction equipment', detail: 'Hand tools, transformers, leads and equipment used in harsher conditions' },
      { value: 'hire-equipment', label: 'Equipment supplied for hire', detail: 'Items inspected before issue or after return under a risk-based regime' },
      { value: 'rented-appliances', label: 'Appliances supplied with rented premises', detail: 'Electrical equipment provided for tenants, guests or residents' },
      { value: 'care-education', label: 'Care, education or public-use equipment', detail: 'Equipment used by staff, residents, pupils, patients or visitors' },
      { value: 'fixed-stationary', label: 'Fixed or stationary electrical equipment', detail: 'Equipment that is not portable but still needs maintenance planning' },
      { value: 'repaired-secondhand', label: 'Repaired, second-hand or returned equipment', detail: 'Equipment whose condition or repair history needs verification' },
      { value: 'none-controlled-equipment', label: 'No electrical equipment under our control', detail: 'Use only after checking employer, landlord and equipment-supply responsibilities' },
      { value: 'unknown-equipment', label: 'Equipment scope is uncertain', detail: 'Ownership, location or equipment categories need an inventory' },
    ],
    signalHeading: 'Which risk and use signals apply?',
    signalHelp: 'These signals help decide whether user checks, formal visual inspection, combined testing or specialist inspection is proportionate.',
    signalOptions: [
      { value: 'frequently-moved', label: 'Frequently moved or handled', detail: 'Leads, plugs and casings receive more wear than static office equipment' },
      { value: 'harsh-environment', label: 'Wet, dusty, outdoor or harsh use', detail: 'The environment raises the chance or consequence of damage' },
      { value: 'visible-damage', label: 'Damage or user concerns reported', detail: 'Damaged equipment should be removed from use and assessed promptly' },
      { value: 'public-or-hired', label: 'Used by the public or hired out', detail: 'Control, condition and user familiarity can vary between uses' },
      { value: 'earthed-equipment', label: 'Class I or earthed equipment', detail: 'Combined inspection and electrical tests may be needed to verify protection' },
      { value: 'repair-or-change', label: 'Repair, modification or change of use', detail: 'The maintenance regime should address the changed condition' },
      { value: 'cannot-disconnect', label: 'Business-critical or difficult to disconnect', detail: 'Access, shutdown and test method must be agreed before attendance' },
      { value: 'unknown-maintenance', label: 'Maintenance regime is unknown', detail: 'No clear inspection frequency, ownership or defect process is recorded' },
      { value: 'no-higher-risk-signals', label: 'None of these higher-risk signals', detail: 'Low-risk equipment may still need user checks or formal visual inspection' },
    ],
    assetLabel: 'Electrical equipment items in scope',
    secondaryLabel: 'Fixed, specialist or shutdown-sensitive items',
    documentationLabel: 'Equipment inventory, previous results and defect records',
    documentationOptions: sharedDocumentation,
    inspectionLabel: 'Current maintenance and inspection position',
    inspectionOptions: [
      { value: 'none', label: 'No inspection or maintenance regime found' },
      { value: 'in-date', label: 'Risk-based regime is recorded and current' },
      { value: 'overdue-or-unknown', label: 'Last checks or next review are unclear' },
      { value: 'new-system', label: 'New site, equipment batch or maintenance regime' },
    ],
    resultResourceHeading: 'PAT is one maintenance tool, not an annual legal certificate',
    resultResourceBody: 'HSE says the law requires equipment to be maintained to prevent danger, but does not prescribe an annual portable appliance test. A suitable regime can combine user checks, formal visual inspection, combined inspection and testing, repair controls and records according to risk.',
    primaryLinks: [
      { label: 'HSE PAT frequently asked questions', detail: 'Legal position, competence, records and risk-based frequency', url: 'https://www.hse.gov.uk/electricity/faq-portable-appliance-testing.htm' },
      { label: 'HSE INDG236', detail: 'Low-risk equipment checks and suggested initial frequencies', url: 'https://www.hse.gov.uk/pubns/indg236.htm' },
      { label: 'Electricity at Work Regulations regulation 4', detail: 'Legal maintenance duty for electrical systems and equipment', url: 'https://www.legislation.gov.uk/uksi/1989/635/regulation/4' },
    ],
    priceEvidence: [
      { label: 'Safety-PAT', url: 'https://safetypat.co.uk/prices-pat-testing/', note: 'Publishes a £25 site rate for up to ten appliances and a per-appliance structure for larger batches in its stated area.' },
      { label: 'PAT Checked', url: 'https://www.patchecked.co.uk/pricing/', note: 'Publishes a £70 minimum call-out and item rates by volume for its Midlands service.' },
      { label: 'London PAT', url: 'https://www.londonpat.com/', note: 'Publishes £80 plus VAT for up to 50 items and volume pricing for Inner London.' },
    ],
  },
}

const labelFor = (definition: ServiceDefinition, value: string) =>
  [...definition.workOptions, ...definition.signalOptions].find((option) => option.value === value)?.label ?? value

export function qualifyService(answers: ServiceAssessmentAnswers): QualificationResult {
  const definition = serviceDefinitions[answers.serviceId]
  const factors: string[] = []
  const positiveWork = answers.workTypes.filter((value) => !value.startsWith('none-'))
  const positiveSignals = answers.riskSignals.filter((value) => !value.startsWith('no-') && !value.startsWith('unknown-'))

  positiveWork.forEach((value) => factors.push(`${labelFor(definition, value)} was selected`))
  positiveSignals.forEach((value) => factors.push(`${labelFor(definition, value)} affects the duty or examination scope`))
  if (answers.inspectionStatus === 'none') factors.push(answers.serviceId === 'pat-testing' ? 'No recorded electrical-equipment inspection or maintenance regime was identified' : 'No previous statutory examination record was identified')
  if (answers.inspectionStatus === 'overdue-or-unknown') factors.push(answers.serviceId === 'pat-testing' ? 'The inspection and maintenance position is uncertain' : 'The examination position is overdue or uncertain')
  if (answers.inspectionStatus === 'new-system') factors.push(answers.serviceId === 'pat-testing' ? 'New equipment or a new site needs visual checking and a maintenance decision' : 'New, installed or assembled equipment needs pre-use consideration')
  if (answers.projectReason === 'change') factors.push('A material change, repair or relocation was identified')
  if (answers.documentationStatus !== 'available') factors.push('Supporting records are missing, incomplete or uncertain')

  let status: QualificationResult['status'] = 'no-obvious-trigger'
  if (answers.serviceId === 'lev') {
    if (positiveWork.length && answers.assetCount > 0) status = 'likely-relevant'
    else if (answers.riskSignals.includes('unknown-system') || positiveWork.length) status = 'may-be-relevant'
  }
  if (answers.serviceId === 'pressure-systems') {
    if (positiveSignals.length) status = 'likely-relevant'
    else if (answers.riskSignals.includes('unknown-fluid') || answers.workTypes.includes('unknown-pressure')) status = 'may-be-relevant'
  }
  if (answers.serviceId === 'loler') {
    if (positiveWork.length && !answers.workTypes.includes('unknown-lifting')) status = 'likely-relevant'
    else if (positiveWork.length || answers.riskSignals.includes('unknown-use')) status = 'may-be-relevant'
  }
  if (answers.serviceId === 'asbestos') {
    const intrusive = answers.workTypes.some((value) => ['refurbishment', 'demolition'].includes(value)) || answers.riskSignals.includes('planned-disturbance')
    const asbestosRiskSignals = ['built-before-2000', 'suspect-material', 'no-register', 'damaged-material', 'previous-findings']
    const dutySignals = answers.workTypes.some((value) => ['occupied-non-domestic', 'common-parts', 'maintenance-work'].includes(value)) && asbestosRiskSignals.some((value) => answers.riskSignals.includes(value))
    if (intrusive || dutySignals) status = 'likely-relevant'
    else if (answers.workTypes.includes('property-acquisition') || answers.workTypes.includes('unknown-use') || answers.riskSignals.includes('unknown-building-age')) status = 'may-be-relevant'
  }
  if (answers.serviceId === 'fire-risk-assessment') {
    const inScopePremises = positiveWork.filter((value) => value !== 'unknown-premises')
    if (inScopePremises.length) status = 'likely-relevant'
    else if (answers.workTypes.includes('unknown-premises')) status = 'may-be-relevant'
  }
  if (answers.serviceId === 'legionella') {
    const inScopeSystems = positiveWork.filter((value) => value !== 'unknown-water-system')
    if (inScopeSystems.length && answers.assetCount > 0) status = 'likely-relevant'
    else if (answers.workTypes.includes('unknown-water-system') || positiveSignals.length) status = 'may-be-relevant'
  }
  if (answers.serviceId === 'pat-testing') {
    const knownEquipment = positiveWork.filter((value) => value !== 'unknown-equipment')
    const strongTestSignals = ['harsh-environment', 'visible-damage', 'public-or-hired', 'earthed-equipment', 'repair-or-change']
    const testSignalSelected = strongTestSignals.some((value) => answers.riskSignals.includes(value))
    const highExposureWork = ['tools-construction', 'hire-equipment', 'repaired-secondhand'].some((value) => answers.workTypes.includes(value))
    if (knownEquipment.length && answers.assetCount > 0 && (testSignalSelected || highExposureWork)) status = 'likely-relevant'
    else if (knownEquipment.length || answers.workTypes.includes('unknown-equipment') || answers.riskSignals.includes('unknown-maintenance')) status = 'may-be-relevant'
  }

  const complexWork = answers.serviceId === 'lev'
    ? ['spray-booth', 'recirculating', 'laboratory-fume'].some((value) => answers.workTypes.includes(value) || answers.riskSignals.includes(value))
    : answers.serviceId === 'pressure-systems'
      ? ['steam-boiler', 'refrigeration', 'process-vessel'].some((value) => answers.workTypes.includes(value))
      : answers.serviceId === 'loler'
        ? ['passenger-lift', 'mewp', 'crane-hoist'].some((value) => answers.workTypes.includes(value))
        : answers.serviceId === 'asbestos'
          ? ['refurbishment', 'demolition'].some((value) => answers.workTypes.includes(value)) || ['planned-disturbance', 'damaged-material'].some((value) => answers.riskSignals.includes(value))
          : answers.serviceId === 'fire-risk-assessment'
            ? ['sleeping-accommodation', 'care-education', 'mixed-use', 'construction-site'].some((value) => answers.workTypes.includes(value)) || ['sleeping-risk', 'vulnerable-occupants', 'dangerous-substances', 'shared-responsibility'].some((value) => answers.riskSignals.includes(value))
            : answers.serviceId === 'legionella'
              ? ['care-healthcare', 'leisure-spa', 'cooling-system', 'process-water'].some((value) => answers.workTypes.includes(value)) || ['recirculation', 'vulnerable-users', 'previous-positive'].some((value) => answers.riskSignals.includes(value))
              : ['tools-construction', 'hire-equipment', 'care-education', 'fixed-stationary'].some((value) => answers.workTypes.includes(value)) || ['harsh-environment', 'visible-damage', 'public-or-hired', 'cannot-disconnect'].some((value) => answers.riskSignals.includes(value))
  const score = positiveWork.length * 2 + positiveSignals.length * 2 + Math.min(answers.assetCount, 5) + (answers.sites > 1 ? 2 : 0) + (complexWork ? 4 : 0)
  const complexity = score >= 10 || answers.sites > 2 || answers.assetCount > 8 || complexWork ? 'complex' : 'standard'

  const scope = answers.serviceId === 'lev'
    ? [
        'Review of the process, contaminant and intended control performance',
        'Physical examination of hoods, ductwork, air cleaner, fan and discharge',
        'Airflow, pressure and capture-performance measurements at identified test points',
        'Comparison with commissioning or previous performance information where available',
        'Assessment of control effectiveness, defects and prioritised remedial actions',
        'A system-specific report, next-test date and information suitable for the LEV record',
      ]
    : answers.serviceId === 'pressure-systems'
      ? [
          'Confirm the system boundary, relevant fluid and safe operating limits',
          'Identify vessels, relevant pipework and every protective device within scope',
          'Draw up, review or certify the written scheme of examination as required',
          'Specify examination nature, preparation, frequency and any special safety measures',
          'Examine the covered parts in accordance with the written scheme',
          'Issue reports, identify repairs and deal with any imminent-danger findings',
        ]
      : answers.serviceId === 'loler' ? [
          'Validate an itemised asset and lifting-accessory register',
          'Confirm examination triggers and intervals for each equipment group',
          'Systematic examination of safety-critical parts by an equipment-competent person',
          'Functional checks or supplementary tests where the competent person requires them',
          'Written Schedule 1 report, next due date and clearly graded defects',
          'Immediate escalation and enforcing-authority reporting where legally required',
        ] : answers.serviceId === 'asbestos' ? [
          'Confirm the dutyholder, premises boundary, building age and available records',
          'Select a management or refurbishment and demolition survey for the actual decision',
          'Agree accessible areas, intrusive access, exclusions, sampling and reinstatement before attendance',
          'Inspect relevant areas and arrange accredited laboratory analysis where samples are taken',
          'Record locations, extent, condition and material or priority assessments as appropriate',
          'Deliver a usable report, register information and clear actions for management or planned work',
        ] : answers.serviceId === 'fire-risk-assessment' ? [
          'Confirm the responsible person, premises boundary, use, occupiers and shared responsibilities',
          'Identify fire hazards, ignition sources, fuel sources and people at risk',
          'Evaluate escape, detection, warning, firefighting, compartmentation and management measures',
          'Consider vulnerable people, dangerous substances and relevant fire-safety systems',
          'Record significant findings, prioritised actions and the emergency-plan implications',
          'Set review triggers and provide a written record the responsible person can maintain',
        ] : answers.serviceId === 'legionella' ? [
          'Confirm the dutyholder, responsible person, premises and water-system boundaries',
          'Build or verify a water-system schematic and asset or outlet inventory',
          'Identify conditions supporting growth, aerosol exposure routes and susceptible people',
          'Evaluate existing temperature, turnover, cleaning, monitoring and maintenance controls',
          'Define a written control scheme with responsibilities, tasks, limits and corrective actions',
          'Record findings, priorities, competence needs and triggers for assessment review',
        ] : [
          'Confirm who controls the equipment, premises, users and maintenance decisions',
          'Build or verify an itemised electrical-equipment inventory and risk groups',
          'Define user checks, formal visual inspection and combined test requirements by risk',
          'Agree shutdowns, access, exclusions and treatment of fixed or specialist equipment',
          'Inspect and test the agreed items with recorded results and clear pass or fail status',
          'Deliver the register, defects, removed-from-use actions and risk-based next-review plan',
        ]

  if (answers.documentationStatus !== 'available') scope.unshift('Reconstruct or verify missing equipment and baseline information before examination')

  return {
    status,
    score,
    triggeredFactors: factors.length ? factors : ['No clear statutory trigger was selected from the information supplied'],
    caveats: [
      `This finder is an initial procurement aid, not a ${definition.name.toLowerCase()} or legal determination.`,
      answers.serviceId === 'asbestos'
        ? 'A competent person must confirm the premises boundary, survey type, access, exclusions and project requirements.'
        : answers.serviceId === 'fire-risk-assessment'
          ? 'The responsible person must confirm that the assessment is suitable and sufficient for the premises, people and risks.'
          : answers.serviceId === 'legionella'
            ? 'A competent person must confirm the water-system boundary, exposure risks, controls and responsible-person arrangements.'
            : answers.serviceId === 'pat-testing'
              ? 'A competent person must confirm the equipment boundary and decide which user checks, visual inspections and electrical tests are proportionate to risk.'
              : 'A competent person must confirm the equipment boundary, operating conditions, exclusions and examination requirements.',
    ],
    scope,
    complexity,
  }
}

export const SERVICE_PRICE_MODELS = {
  lev: {
    version: 'published-provider-calibration-2026-08-31', baseVisit: 225, perSystem: 185, perExtraPoint: 28,
    complexSystem: 220, missingBaseline: 90, additionalSite: 190, spread: 0.24,
  },
  'pressure-systems': {
    version: 'simple-system-calibration-2026-08-31', baseVisit: 280, perAsset: 115, perProtectiveDevice: 32,
    newWrittenScheme: 240, complexSystem: 380, additionalSite: 230, spread: 0.3,
  },
  loler: {
    version: 'published-provider-calibration-2026-08-31', baseVisit: 180, perMainItem: 82, perAccessory: 11,
    peopleLiftingItem: 35, complexEquipment: 95, additionalSite: 175, spread: 0.25,
  },
  asbestos: {
    version: 'published-provider-calibration-2026-09-10', baseVisit: 350, perBuilding: 250, perSample: 35,
    intrusiveSurvey: 250, complexPremises: 450, additionalSite: 300, spread: 0.28,
  },
  'fire-risk-assessment': {
    version: 'published-provider-calibration-2026-09-11', baseVisit: 200, perFloor: 65, perOccupancy: 45,
    sleepingOrVulnerable: 250, complexPremises: 350, additionalSite: 200, spread: 0.3,
  },
  legionella: {
    version: 'published-provider-calibration-2026-09-12', baseVisit: 250, perOutlet: 8, perMainAsset: 45,
    higherRiskSystem: 300, complexSystem: 400, additionalSite: 225, spread: 0.28,
  },
  'pat-testing': {
    version: 'published-provider-calibration-2026-09-13', baseVisit: 55, perItem: 1.2, perSpecialistItem: 6,
    complexSite: 65, additionalSite: 50, spread: 0.25,
  },
} as const

export function estimateServicePrice(
  answers: ServiceAssessmentAnswers,
  result = qualifyService(answers),
): PriceEstimate {
  const factors: PriceEstimate['factors'] = []
  if (answers.serviceId === 'lev') {
    const model = SERVICE_PRICE_MODELS.lev
    factors.push({ label: 'Site attendance and report setup', amount: model.baseVisit })
    factors.push({ label: `${answers.assetCount} LEV system${answers.assetCount === 1 ? '' : 's'}`, amount: answers.assetCount * model.perSystem })
    if (answers.secondaryCount > 5) factors.push({ label: `${answers.secondaryCount - 5} extraction points above the first five`, amount: (answers.secondaryCount - 5) * model.perExtraPoint })
    if (result.complexity === 'complex') factors.push({ label: 'Complex system or measurement allowance', amount: model.complexSystem })
    if (answers.documentationStatus !== 'available') factors.push({ label: 'Missing baseline or commissioning information', amount: model.missingBaseline })
    if (answers.sites > 1) factors.push({ label: `${answers.sites - 1} additional site attendance allowance`, amount: (answers.sites - 1) * model.additionalSite })
  } else if (answers.serviceId === 'pressure-systems') {
    const model = SERVICE_PRICE_MODELS['pressure-systems']
    factors.push({ label: 'Competent-person attendance and reporting', amount: model.baseVisit })
    factors.push({ label: `${answers.assetCount} pressure plant item${answers.assetCount === 1 ? '' : 's'}`, amount: answers.assetCount * model.perAsset })
    if (answers.secondaryCount) factors.push({ label: `${answers.secondaryCount} protective device${answers.secondaryCount === 1 ? '' : 's'} to identify`, amount: answers.secondaryCount * model.perProtectiveDevice })
    if (answers.inspectionStatus === 'none' || answers.inspectionStatus === 'new-system') factors.push({ label: 'New written-scheme preparation allowance', amount: model.newWrittenScheme })
    if (result.complexity === 'complex') factors.push({ label: 'Complex pressure-system allowance', amount: model.complexSystem })
    if (answers.sites > 1) factors.push({ label: `${answers.sites - 1} additional site attendance allowance`, amount: (answers.sites - 1) * model.additionalSite })
  } else if (answers.serviceId === 'loler') {
    const model = SERVICE_PRICE_MODELS.loler
    factors.push({ label: 'Minimum site attendance and reporting', amount: model.baseVisit })
    factors.push({ label: `${answers.assetCount} main lifting-equipment item${answers.assetCount === 1 ? '' : 's'}`, amount: answers.assetCount * model.perMainItem })
    if (answers.secondaryCount) factors.push({ label: `${answers.secondaryCount} lifting accessor${answers.secondaryCount === 1 ? 'y' : 'ies'}`, amount: answers.secondaryCount * model.perAccessory })
    if (answers.riskSignals.includes('lifts-people')) factors.push({ label: 'People-lifting examination allowance', amount: answers.assetCount * model.peopleLiftingItem })
    if (result.complexity === 'complex') factors.push({ label: 'Complex equipment allowance', amount: model.complexEquipment })
    if (answers.sites > 1) factors.push({ label: `${answers.sites - 1} additional site attendance allowance`, amount: (answers.sites - 1) * model.additionalSite })
  } else if (answers.serviceId === 'asbestos') {
    const model = SERVICE_PRICE_MODELS.asbestos
    factors.push({ label: 'Survey planning, attendance and report setup', amount: model.baseVisit })
    factors.push({ label: `${answers.assetCount} building or block${answers.assetCount === 1 ? '' : 's'} in scope`, amount: answers.assetCount * model.perBuilding })
    if (answers.secondaryCount) factors.push({ label: `${answers.secondaryCount} sample or suspect-location allowance`, amount: answers.secondaryCount * model.perSample })
    if (answers.workTypes.some((value) => ['refurbishment', 'demolition'].includes(value)) || answers.riskSignals.includes('planned-disturbance')) factors.push({ label: 'Intrusive refurbishment or demolition survey allowance', amount: model.intrusiveSurvey })
    if (result.complexity === 'complex') factors.push({ label: 'Complex premises, access or risk allowance', amount: model.complexPremises })
    if (answers.sites > 1) factors.push({ label: `${answers.sites - 1} additional site attendance allowance`, amount: (answers.sites - 1) * model.additionalSite })
  } else if (answers.serviceId === 'fire-risk-assessment') {
    const model = SERVICE_PRICE_MODELS['fire-risk-assessment']
    factors.push({ label: 'Assessment planning, attendance and report setup', amount: model.baseVisit })
    factors.push({ label: `${answers.assetCount} floor or level${answers.assetCount === 1 ? '' : 's'} in scope`, amount: answers.assetCount * model.perFloor })
    if (answers.secondaryCount) factors.push({ label: `${answers.secondaryCount} separate occupanc${answers.secondaryCount === 1 ? 'y' : 'ies'}`, amount: answers.secondaryCount * model.perOccupancy })
    if (answers.riskSignals.some((value) => ['sleeping-risk', 'vulnerable-occupants'].includes(value))) factors.push({ label: 'Sleeping or vulnerable-occupant assessment allowance', amount: model.sleepingOrVulnerable })
    if (result.complexity === 'complex') factors.push({ label: 'Complex premises or fire-risk allowance', amount: model.complexPremises })
    if (answers.sites > 1) factors.push({ label: `${answers.sites - 1} additional site attendance allowance`, amount: (answers.sites - 1) * model.additionalSite })
  } else if (answers.serviceId === 'legionella') {
    const model = SERVICE_PRICE_MODELS.legionella
    factors.push({ label: 'Assessment planning, attendance and report setup', amount: model.baseVisit })
    factors.push({ label: `${answers.assetCount} water outlet${answers.assetCount === 1 ? '' : 's'} in scope`, amount: answers.assetCount * model.perOutlet })
    if (answers.secondaryCount) factors.push({ label: `${answers.secondaryCount} tank, calorifier or main asset${answers.secondaryCount === 1 ? '' : 's'}`, amount: answers.secondaryCount * model.perMainAsset })
    if (answers.workTypes.some((value) => ['care-healthcare', 'leisure-spa', 'cooling-system'].includes(value)) || answers.riskSignals.includes('vulnerable-users')) factors.push({ label: 'Higher-risk system or susceptible-person allowance', amount: model.higherRiskSystem })
    if (result.complexity === 'complex') factors.push({ label: 'Complex water-system allowance', amount: model.complexSystem })
    if (answers.sites > 1) factors.push({ label: `${answers.sites - 1} additional site attendance allowance`, amount: (answers.sites - 1) * model.additionalSite })
  } else {
    const model = SERVICE_PRICE_MODELS['pat-testing']
    factors.push({ label: 'Minimum attendance, setup and register', amount: model.baseVisit })
    factors.push({ label: `${answers.assetCount} electrical equipment item${answers.assetCount === 1 ? '' : 's'}`, amount: answers.assetCount * model.perItem })
    if (answers.secondaryCount) factors.push({ label: `${answers.secondaryCount} fixed, specialist or shutdown-sensitive item${answers.secondaryCount === 1 ? '' : 's'}`, amount: answers.secondaryCount * model.perSpecialistItem })
    if (result.complexity === 'complex') factors.push({ label: 'Complex access, equipment or scheduling allowance', amount: model.complexSite })
    if (answers.sites > 1) factors.push({ label: `${answers.sites - 1} additional site attendance allowance`, amount: (answers.sites - 1) * model.additionalSite })
  }

  const midpoint = factors.reduce((total, factor) => total + factor.amount, 0)
  const spread = SERVICE_PRICE_MODELS[answers.serviceId].spread
  const lowFloor = answers.serviceId === 'pat-testing' ? 50 : 150
  const highFloor = answers.serviceId === 'pat-testing' ? 75 : 200
  return {
    low: Math.max(lowFloor, Math.round((midpoint * (1 - spread)) / 25) * 25),
    high: Math.max(highFloor, Math.round((midpoint * (1 + spread)) / 25) * 25),
    currency: 'GBP',
    factors,
    assumptions: [
      'One planned visit per site during normal working hours',
      answers.serviceId === 'asbestos' ? 'Premises and agreed survey areas are safely accessible' : answers.serviceId === 'fire-risk-assessment' ? 'Premises, records and agreed areas are accessible during the assessment' : answers.serviceId === 'legionella' ? 'Water outlets, plant areas and available records are accessible during the assessment' : answers.serviceId === 'pat-testing' ? 'Equipment is available, identifiable, safely accessible and can be disconnected as agreed' : 'Equipment is available, identifiable and safely accessible for examination',
      'VAT, repairs, replacement parts, specialist access and intrusive testing are excluded',
      'Calibration sources cover only some simple/common jobs and are not an awarded-quote market benchmark',
      'This is deterministic Vendor Atlas planning guidance, not a supplier quotation',
    ],
  }
}

export function defaultServiceAnswers(serviceId: IndustrialServiceId): ServiceAssessmentAnswers {
  return {
    serviceId,
    sector: 'manufacturing',
    workTypes: [],
    riskSignals: [],
    assetCount: 1,
    secondaryCount: serviceId === 'lev' ? 1 : serviceId === 'asbestos' ? 4 : serviceId === 'fire-risk-assessment' ? 1 : serviceId === 'legionella' ? 1 : 0,
    sites: 1,
    size: 'small',
    documentationStatus: 'unknown',
    inspectionStatus: 'overdue-or-unknown',
    projectReason: 'first-examination',
    region: 'midlands',
    postcode: '',
    timescale: 'one-month',
  }
}
