import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import Link from 'next/link'
import { ToolkitActions } from '../../../src/components/ToolkitActions'

export const metadata: Metadata = {
  title: 'DSEAR buying toolkit and quote comparison template',
  description: 'Prepare a DSEAR project brief, test specialist competence and compare quotations on the same scope.',
  alternates: { canonical: '/dsear/buying-toolkit' },
}

const Check = ({ children }: { children: ReactNode }) => <li><span className="print-checkbox" aria-hidden="true">□</span>{children}</li>

export default function BuyingToolkitPage() {
  return (
    <article className="content-page toolkit-page">
      <header className="content-hero"><div className="shell narrow"><span className="eyebrow">Buyer pack · version 1.0</span><h1>Buy a DSEAR assessment on comparable terms</h1><p className="lead">Use one brief, ask every provider the same competence questions and compare what is actually included—not just the fee.</p><ToolkitActions /></div></header>
      <div className="shell toolkit-summary"><section className="decision-panel"><span className="eyebrow">The standard</span><h2>A comparable quote must answer five things</h2><ol><li>Who will do the work and why are they competent for these hazards?</li><li>Which sites, processes, substances and documents are in scope?</li><li>What site work, analysis, classification and drawings are included?</li><li>What report, action plan and follow-up will be delivered?</li><li>What is excluded, assumed or separately chargeable?</li></ol></section></div>
      <div className="shell toolkit-sections">
        <section className="toolkit-sheet"><div className="sheet-number">01</div><div><h2>Information to assemble before requesting quotes</h2><p>Mark unknown items explicitly. A supplier can price discovery work; it cannot price an assumption you have not disclosed.</p><ul className="checklist"><Check>Site address, number of buildings and approximate operational floor area</Check><Check>Short description of each process, including cleaning, maintenance and foreseeable abnormal work</Check><Check>Dangerous-substance inventory with quantities, locations and current safety data sheets</Check><Check>Site and process layouts, PFDs or P&amp;IDs where available</Check><Check>Ventilation, extraction, gas detection and isolation information</Check><Check>Existing DSEAR, COSHH, fire, HAZOP or related assessments</Check><Check>Existing hazardous-area drawings and Ex-equipment registers</Check><Check>Incident, near-miss, enforcement, insurer or planned-change context</Check><Check>Required timescale, operational access limits and shutdown constraints</Check></ul></div></section>
        <section className="toolkit-sheet"><div className="sheet-number">02</div><div><h2>Project brief</h2><div className="brief-fields"><p><strong>Business and site:</strong> ______________________________________________</p><p><strong>Reason for commissioning:</strong> first assessment / change / new installation / review</p><p><strong>Substances and hazards:</strong> ________________________________________</p><p><strong>Processes and release points:</strong> ____________________________________</p><p><strong>Known or possible zoning need:</strong> ___________________________________</p><p><strong>Documents available:</strong> ___________________________________________</p><p><strong>Sites and areas in scope:</strong> ________________________________________</p><p><strong>Target visit and report date:</strong> _____________________________________</p></div><h3>Required quotation format</h3><ul className="checklist"><Check>Named assessor and proposed supporting team</Check><Check>Scope and method, including site attendance and document review</Check><Check>Deliverables, file formats and draft/final review process</Check><Check>HAC schedules, calculations and drawings included or clearly excluded</Check><Check>Assumptions, buyer dependencies and exclusions</Check><Check>Fixed fee or day-rate basis, VAT, travel and additional-work rates</Check><Check>Proposed dates and validity period</Check></ul></div></section>
        <section className="toolkit-sheet"><div className="sheet-number">03</div><div><h2>Competence and evidence questions</h2><p>DSEAR does not prescribe one universal assessor certificate. Test competence against the actual work you are buying.</p><ol className="question-list"><li>Who is the named assessor, and what relevant training, qualifications and current professional standing can you evidence?</li><li>Which recent projects involved comparable substances, release conditions and process complexity?</li><li>Who will undertake hazardous area classification and produce calculations or drawings if it is required?</li><li>Which standards and industry guidance do you expect to use, and where might a specialist test or separate discipline be needed?</li><li>Can you provide current professional indemnity and public liability evidence appropriate to the project?</li><li>How do you quality-review reports and deal with disputed assumptions or factual corrections?</li><li>Will you declare subcontractors, conflicts, referral arrangements or product-sales interests?</li></ol></div></section>
        <section className="toolkit-sheet landscape-sheet"><div className="sheet-number">04</div><div><h2>Comparable quote scorecard</h2><div className="table-scroll"><table className="comparison-table"><thead><tr><th>Comparison point</th><th>Provider A</th><th>Provider B</th><th>Provider C</th></tr></thead><tbody>{['Named assessor and relevant competence','Similar hazard/process evidence','Site work included','Substance inventory and release review','HAC schedules/calculations','HAC drawings','Electrical/non-electrical equipment review','Prioritised action plan','Draft review and debrief','Travel, VAT and expenses','Exclusions and additional rates','Delivery date','Total comparable fee'].map((row) => <tr key={row}><th>{row}</th><td></td><td></td><td></td></tr>)}</tbody></table></div><p className="toolkit-warning"><strong>Do not add the scores blindly.</strong> A missing competence or scope requirement can be a stop condition, not a small numerical disadvantage.</p></div></section>
        <section className="toolkit-sheet"><div className="sheet-number">05</div><div><h2>Report acceptance check</h2><ul className="checklist"><Check>Correct sites, processes, substances, quantities and operating conditions</Check><Check>Evidence sources and material assumptions are visible</Check><Check>Normal work, cleaning, maintenance and credible abnormal events are considered</Check><Check>Release scenarios, ventilation and ignition sources are connected to conclusions</Check><Check>Hazardous-area classification is included where needed and absent only for an explained reason</Check><Check>Drawings and schedules agree with the written report</Check><Check>Existing controls and gaps are distinguished</Check><Check>Actions are specific, prioritised and assigned sensible timescales</Check><Check>Unresolved tests, data gaps and specialist dependencies are explicit</Check><Check>Draft factual corrections and final debrief have been completed</Check></ul></div></section>
        <section className="toolkit-sheet"><div className="sheet-number">06</div><div><h2>Review triggers after appointment</h2><p>Keep the assessment connected to operational change. Regulation 5 requires review where there is reason to suspect the assessment is no longer valid or where there has been a significant change.</p><ul className="checklist"><Check>New substance, supplier formulation or materially different quantity</Check><Check>New plant, process, layout, ventilation or extraction arrangement</Check><Check>Changed release point, operating temperature, pressure or transfer method</Check><Check>Modified electrical or mechanical equipment in or near a hazardous area</Check><Check>Fire, explosion, loss of containment, near miss or control failure</Check><Check>Evidence that an assumption, drawing or safety-data basis is no longer current</Check></ul><p>Primary basis: <a href="https://www.legislation.gov.uk/uksi/2002/2776/regulation/5" target="_blank" rel="noreferrer">DSEAR 2002, Regulation 5 <span aria-hidden>↗</span></a> and <a href="https://www.hse.gov.uk/pubns/priced/l138.pdf" target="_blank" rel="noreferrer">HSE L138 <span aria-hidden>↗</span></a>.</p></div></section>
      </div>
      <div className="shell toolkit-footer-note"><p><strong>Vendor Atlas buyer standard v1.0 · 31 August 2026.</strong> This pack is procurement support, not a risk assessment, legal advice or a competence certification. Adapt it to the scale and hazards of the work.</p><Link href="/dsear/suppliers">Browse the evidence directory →</Link></div>
    </article>
  )
}
