import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy and analytics",
  description: "How the Vendor Atlas pilot handles quote enquiries and analytics.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return <article className="content-page"><header className="content-hero"><div className="shell narrow"><span className="eyebrow">Pilot notice</span><h1>Privacy and analytics</h1><p className="lead">Vendor Atlas is a product pilot operated by Cloudable Ltd. This notice explains the limited data used by the DSEAR finder.</p></div></header><div className="shell article-grid"><div><section><h2>Assessment answers</h2><p>Your questionnaire answers are used in your browser to calculate the qualification indication, estimate and supplier matches. They are included in a project brief only if you choose to submit one.</p></section><section><h2>Project briefs</h2><p>When you submit a brief, we store the project answers, company name, contact name, business email, optional phone number, consent record, shortlist and estimate. A person will review the request and may contact you about arranging comparable quotations. Your contact details are not automatically sent to suppliers.</p></section><section><h2>Pilot measurement</h2><p>We record limited first-party journey events, such as opening the page, starting or completing the assessment, viewing a supplier and submitting a project brief. These records contain the event name, time, page and limited result metadata; they do not contain the questionnaire answers or contact details. We do not use advertising cookies or a third-party analytics tracker.</p></section><section><h2>Retention and requests</h2><p>Pilot project briefs and measurement records will be reviewed and removed when no longer needed for follow-up or product validation. To ask about, correct or delete a submitted request, email <a href="mailto:hello@cloudable.biz">hello@cloudable.biz</a>.</p></section></div><aside className="sources"><strong>Operator</strong><p>Cloudable Ltd<br/>Company number 12104646<br/>Vendor Atlas pilot</p><a href="mailto:hello@cloudable.biz">hello@cloudable.biz</a><p>Last updated 31 August 2026.</p></aside></div></article>;
}
