export interface DecisionPage { path: string; title: string; description: string; eyebrow: string; intro: string; sections: Array<{ heading: string; body: string; points?: string[] }>; sources: Array<{ label: string; url: string }> }

const hse = { label: 'HSE: DSEAR in detail', url: 'https://www.hse.gov.uk/fireandexplosion/dsear-background.htm' }
const law = { label: 'The Dangerous Substances and Explosive Atmospheres Regulations 2002', url: 'https://www.legislation.gov.uk/uksi/2002/2776/contents' }
const acop = { label: 'HSE L138: DSEAR Approved Code of Practice and guidance', url: 'https://www.hse.gov.uk/pubns/priced/l138.pdf' }

export const pages: DecisionPage[] = [
  { path: '/dsear', title: 'DSEAR: a practical starting point', description: 'Understand the DSEAR duty, likely assessment scope and how to find a competent specialist.', eyebrow: 'DSEAR overview', intro: 'DSEAR concerns safety risks from dangerous substances at work: fire, explosion and similar energetic events. The first practical question is what substances are present and how they are used—not what your industry is called.', sections: [
    { heading: 'When to look more closely', body: 'If dangerous substances are present or liable to be present, the employer must make a suitable and sufficient assessment. HSE says liquids, gases, vapours and dusts can all be dangerous substances.', points: ['Identify substances and safety data', 'Map the work activities and quantities', 'Consider releases, ventilation and ignition sources', 'Record significant findings where required'] },
    { heading: 'What this finder does', body: 'Vendor Atlas turns a short set of procurement questions into an initial relevance indication, explainable scope, planning price and evidence-backed supplier shortlist. It does not perform the legal assessment.' },
  ], sources: [hse, law, acop] },
  { path: '/dsear/do-i-need-a-dsear-assessment', title: 'Do I need a DSEAR assessment?', description: 'A decision aid for checking when dangerous substances may trigger the need for a DSEAR risk assessment.', eyebrow: 'Decision guide', intro: 'You are likely to need to assess DSEAR risks when a dangerous substance is or could be present at a workplace. The exact answer depends on the substance, quantity, process, potential release and possible consequences.', sections: [
    { heading: 'Strong indicators', body: 'Common indicators include flammable liquids or gases, solvent use, fuels, potentially explosive dust clouds, gases under pressure and substances capable of energetic thermal events.', points: ['Spraying or coating with solvent-borne products', 'Decanting or transferring fuel or flammable liquid', 'Producing or extracting fine wood, food or metal dust', 'Using LPG or other flammable gas', 'New or materially changed plant involving these hazards'] },
    { heading: 'What the law asks you to consider', body: 'Regulation 5 includes hazardous properties, supplier safety information, work processes, amounts, combined substances, storage, maintenance, explosive atmospheres, ignition sources and anticipated effects.' },
  ], sources: [law, hse] },
  { path: '/dsear/cost', title: 'What might a DSEAR assessment cost?', description: 'See the practical factors that shape DSEAR assessment quotations and get an explainable planning estimate.', eyebrow: 'Cost guide', intro: 'There is no official tariff. A useful estimate has to reflect the number of sites, processes, hazard types, available drawings, survey access and whether hazardous area classification is likely.', sections: [
    { heading: 'Vendor Atlas pricing approach', body: 'The calculator starts with a site-size allowance, then adds visible amounts for additional sites, multiple hazard types, specialist processes, combustible dust and design-stage review. The range is planning guidance—not a supplier quote.' },
    { heading: 'Compare like with like', body: 'Ask each provider to state what the price includes.', points: ['Site visit and travel', 'Substance inventory review', 'Hazardous area classification and drawings where required', 'Equipment suitability review', 'Prioritised actions and report revision', 'VAT, testing and follow-on design work'] },
  ], sources: [hse, acop] },
  { path: '/dsear/who-can-carry-out-a-dsear-assessment', title: 'Who can carry out a DSEAR assessment?', description: 'How to select a competent person or consultancy for DSEAR assessment and hazardous area work.', eyebrow: 'Supplier selection', intro: 'The employer retains the duty, but can appoint competent help. Competence should fit the actual hazards and work: a simple flammable-store review is not the same as complex dust zoning or a new process plant.', sections: [
    { heading: 'Evidence to request', body: 'Vendor Atlas records what can be evidenced publicly, but you should complete project-specific pre-qualification.', points: ['Relevant project examples and hazard experience', 'Named assessor competence and professional evidence', 'Professional indemnity and public liability insurance', 'Scope, exclusions and applicable standards', 'Sample deliverable or report structure', 'Conflict-of-interest and remedial-work position'] },
    { heading: 'What a comparable quotation needs', body: 'Give every supplier the same process, site, hazard, location, timescale and existing-document information. Ask them to identify assumptions and exclusions.' },
  ], sources: [acop, hse] },
  { path: '/dsear/for-manufacturing', title: 'DSEAR for manufacturing', description: 'A focused DSEAR decision guide for manufacturing operations involving flammables, gases, dusts or fuels.', eyebrow: 'Sector guide', intro: 'Manufacturing can bring several DSEAR-relevant hazards together: solvent use, coating, fuel systems, gases, powders, dust extraction and ignition-capable equipment.', sections: [
    { heading: 'Map the process, not just the stores', body: 'Assessment should follow substances through receipt, storage, transfer, use, waste and maintenance. Normal operation and foreseeable abnormal events both matter.' },
    { heading: 'Information to prepare', body: 'A specialist will work faster with current layouts, safety data sheets, inventories, extraction information, equipment records and a clear description of process changes.' },
  ], sources: [hse, law] },
  { path: '/dsear/for-breweries', title: 'DSEAR for breweries and distilleries', description: 'Check DSEAR considerations around ethanol, LPG, gases, grain dust and cleaning chemicals in drink production.', eyebrow: 'Sector guide', intro: 'Breweries and distilleries can involve alcohol vapour, LPG or natural gas, carbon dioxide under pressure and combustible grain or malt dust. Not every area is hazardous; conditions and quantities matter.', sections: [
    { heading: 'Typical review areas', body: 'A review may cover spirit or alcohol handling, grain transfer, mills and dust collection, gas systems, charging points, cleaning products, ventilation and ignition controls.' },
    { heading: 'Keep health and safety duties distinct', body: 'DSEAR addresses harmful physical effects such as fire and explosion. COSHH addresses health risks. A substance or process can require consideration under both regimes.' },
  ], sources: [hse, acop] },
  { path: '/dsear/for-woodworking', title: 'DSEAR for woodworking', description: 'A practical guide to DSEAR questions for wood dust, extraction systems, finishing products and workshops.', eyebrow: 'Sector guide', intro: 'Fine wood dust can form an explosive atmosphere when dispersed in air. Finishing processes may also involve flammable solvents, paints or lacquers.', sections: [
    { heading: 'Look at generation and collection', body: 'Saws, sanders, ductwork, filters, cyclones, waste collection and housekeeping all affect the risk. Dust inside extraction equipment can differ from dust on open workshop surfaces.' },
    { heading: 'Evidence a specialist may need', body: 'Prepare dust and material information, extraction drawings, cleaning arrangements, maintenance records, equipment details and any previous zoning or explosion-protection work.' },
  ], sources: [hse, acop] },
  { path: '/dsear/for-spray-booths', title: 'DSEAR for spray booths', description: 'Decision support for spray-painting, coating, mixing and solvent-cleaning operations.', eyebrow: 'Process guide', intro: 'Spraying can create a flammable mist or vapour, while mixing, cleaning and waste handling can introduce separate release sources.', sections: [
    { heading: 'The booth is not the whole process', body: 'Consider the paint or coating store, mixing point, gun cleaning, contaminated waste, ventilation failure, maintenance and equipment inside or near any classified zone.' },
    { heading: 'Useful quotation inputs', body: 'Share product safety data, booth and extraction specifications, layout, throughput, cleaning method, operating hours and existing electrical or zoning information.' },
  ], sources: [hse, law] },
  { path: '/dsear/combustible-dust', title: 'Combustible dust and DSEAR', description: 'Understand why fine wood, food, metal and other dusts can require specialist DSEAR review.', eyebrow: 'Hazard guide', intro: 'HSE states that any dust capable of exploding when spread in air as a cloud can be a dangerous substance. Material, particle size, process and containment all affect the assessment.', sections: [
    { heading: 'Why dust work can be specialist', body: 'Assessment may need material test data, release-source identification, dust-cloud and layer consideration, extraction review, zoning, ignition-source assessment and explosion protection.' },
    { heading: 'Do not infer explosibility from the product name alone', body: 'A competent assessment should use suitable substance or test information and the actual process conditions. Vendor Atlas treats a selected dust process as a complexity signal, not a definitive conclusion.' },
  ], sources: [hse, acop] },
  { path: '/dsear/lithium-batteries', title: 'Lithium batteries and DSEAR', description: 'A cautious decision guide for battery charging, storage, processing and thermal-event risk.', eyebrow: 'Hazard guide', intro: 'Battery work is not automatically one uniform DSEAR scenario. Chemistry, scale, charging, damage, processing, gas release and thermal-event potential should be examined by someone competent for the operation.', sections: [
    { heading: 'Describe the operation precisely', body: 'Distinguish routine charging from bulk storage, testing, repacking, damaged-battery handling and recycling or shredding. The substances and failure modes are different.' },
    { heading: 'Use the finder as an escalation check', body: 'The wizard flags battery work for professional scoping but does not declare a zone, equipment category or legal conclusion.' },
  ], sources: [hse, acop] },
  { path: '/dsear/dsear-vs-coshh', title: 'DSEAR vs COSHH', description: 'Understand the practical difference between DSEAR safety risks and COSHH health risks.', eyebrow: 'Comparison guide', intro: 'DSEAR and COSHH ask different questions. DSEAR focuses on harmful physical effects from fire, explosion and similar events. COSHH focuses on health risks from exposure to hazardous substances.', sections: [
    { heading: 'The same substance can appear in both assessments', body: 'A solvent may create inhalation or skin-exposure risk under COSHH and fire or explosion risk under DSEAR. Completing one assessment does not automatically answer the other.' },
    { heading: 'A useful document check', body: 'Look for distinct consideration of substance health hazards, physical hazards, exposure controls, releases, ignition sources, fire/explosion controls and emergency arrangements.' },
  ], sources: [hse, acop] },
]
