import type { ReactNode } from 'react'
import Link from 'next/link'
import { ToolkitActions } from './ToolkitActions'
import { serviceDefinitions } from '../domain/service-assessment'
import type { ServiceId } from '../domain/types'

type IndustrialServiceId = Exclude<ServiceId, 'dsear'>
const Check = ({ children }: { children: ReactNode }) => <li><span className="print-checkbox" aria-hidden="true">□</span>{children}</li>

const toolkitData = {
  lev: {
    title: 'Buy an LEV thorough examination on comparable terms', lead: 'Use one system schedule, ask every examiner the same competence questions and compare the full TExT deliverable—not merely a certificate or day rate.',
    standard: ['Who will examine each system and what comparable LEV experience can they evidence?', 'Which fans, hoods, test points and operating conditions are included?', 'How will missing commissioning or benchmark information be handled?', 'What measurements, control judgement, report and defect priorities will be delivered?', 'What servicing, repairs, retesting, access, travel and VAT are excluded?'],
    assemble: ['Site address, access arrangements, shifts and shutdown constraints', 'LEV system list with fan/system identifiers and every connected hood or extraction point', 'Process and contaminant controlled by each system', 'Commissioning report, design performance, diagrams and user manual where available', 'Previous TExT reports, measurements, due dates and unresolved actions', 'LEV logbook, routine check, service, filter and repair records', 'Recirculation, air-cleaning, discharge, make-up-air and access details', 'Desired visit and report dates'],
    competence: ['Who is the named examiner and what current LEV examination training and experience can they evidence?', 'Which comparable systems and contaminants has that person examined?', 'Which calibrated instruments and test methods will be used?', 'How will the examiner establish performance where commissioning data is missing?', 'Can you provide a redacted comparable report showing measurements, judgement and prioritised actions?', 'How are examination conclusions separated from repair or product sales?', 'What professional indemnity and public liability evidence applies?'],
    comparison: ['Named examiner and relevant competence', 'Every system and hood included', 'Physical examination', 'Airflow, pressure and capture measurements', 'Benchmark and commissioning-data method', 'Control-effectiveness judgement', 'Photographs, schematic and test points', 'Prioritised defect actions', 'Retest arrangements', 'Travel, access, VAT and exclusions', 'Total comparable fee'],
    acceptance: ['Correct site, process, contaminant and complete system identity', 'Every hood and measurement point is traceable', 'Operating conditions and instruments are recorded', 'Measured values are compared with intended or justified performance', 'Physical condition and control effectiveness are judged separately', 'Defects and actions are specific, prioritised and understandable', 'Missing baseline data and limitations remain visible', 'Next TExT date and any shorter interval are explicit'],
    source: 'https://books.hse.gov.uk/gempdf/hsg258.pdf', sourceLabel: 'HSE HSG258',
  },
  'pressure-systems': {
    title: 'Buy PSSR written-scheme and examination work on comparable terms', lead: 'Use one system inventory, distinguish written-scheme work from examination and maintenance, and test competence against the real pressure-system complexity.',
    standard: ['Which competent-person function and pressure-system category will the provider cover?', 'Which vessels, pipework, protective devices and sites are in scope?', 'Is the price for inventory, written-scheme creation or review, examination—or all three?', 'What preparation, isolation, strip-down, specialist tests and reports are included?', 'What maintenance, repairs, recommissioning, travel and VAT are excluded?'],
    assemble: ['Site address, user or owner details and responsible contacts', 'System description, fluid, normal and safe operating pressure and temperature', 'Equipment schedule, capacities, plates, manufacturer data and serial numbers', 'Drawings showing vessels, associated pipework and protective devices', 'Current written scheme and previous examination reports', 'Maintenance, repair, modification and operating history', 'Isolation, cooling, drainage, opening, cleaning and access arrangements', 'Desired examination window and production constraints'],
    competence: ['Which organisation and named engineer will certify or prepare the written scheme?', 'Which system category and relevant-fluid experience can they evidence?', 'What current inspection-body accreditation scope or equivalent evidence applies?', 'How are independence, authority to stop use and quality review protected?', 'Who takes responsibility for specialist or non-destructive testing results?', 'Can you provide a redacted written scheme and examination report for comparable plant?', 'What professional indemnity and public liability evidence applies?'],
    comparison: ['Competent-person function stated', 'System inventory and boundary confirmation', 'Written-scheme creation or review', 'Vessels, pipework and protective devices included', 'Examination nature and intervals', 'Preparation and isolation responsibilities', 'Specialist tests and interpretation', 'Report and danger-escalation process', 'Travel, access, VAT and exclusions', 'Maintenance/recommissioning separation', 'Total comparable fee'],
    acceptance: ['Correct user or owner, site and system boundary', 'Relevant fluid, safe limits and operating conditions are recorded', 'Every protective device and danger-critical part is addressed', 'Examination nature, preparation and maximum interval are clear', 'Scheme is certified as suitable by the responsible competent person', 'Examination report traces directly to the scheme and equipment', 'Repairs, imminent danger and next steps are explicit', 'Scheme review triggers and records are understandable'],
    source: 'https://www.hse.gov.uk/pubns/indg178.htm', sourceLabel: 'HSE INDG178',
  },
  loler: {
    title: 'Buy LOLER thorough examinations on comparable terms', lead: 'Use one itemised asset register, identify people-lifting and accessory intervals, and compare equipment-specific competence and reports—not a vague site rate.',
    standard: ['Who will examine each equipment category and why are they competent for it?', 'Which main assets, attachments and lifting accessories are included?', 'Which interval, first-use, installation or exceptional-event trigger applies?', 'What examination, supplementary tests, Schedule 1 report and defect process are included?', 'What PUWER inspection, servicing, repair, retesting, travel and VAT are excluded?'],
    assemble: ['Site address, access, shifts, operational restrictions and responsible person', 'Main equipment register with type, make, model, serial number, SWL and location', 'Lifting-accessory register or kit list with identifiers and dates', 'Whether each item lifts people, goods or both', 'Declarations, previous reports, next dates and any examination schemes', 'Damage, overload, repair, modification, relocation or long-disuse history', 'Maintenance and PUWER inspection records', 'Desired visit, report and defect-response times'],
    competence: ['Who is the named examiner for each equipment category?', 'What practical and theoretical knowledge and comparable experience can they evidence?', 'How is independence from maintenance or repair work maintained?', 'Which standards, discard criteria and specialist tests will be used?', 'Can you provide a redacted Schedule 1 report with defect grading and next dates?', 'How are serious defects communicated and sent to the enforcing authority where required?', 'What professional indemnity and public liability evidence applies?'],
    comparison: ['Named examiner by equipment category', 'Main equipment schedule complete', 'Accessory schedule complete', 'People-lifting use and intervals confirmed', 'Installation/exceptional triggers addressed', 'Supplementary testing included or excluded', 'Schedule 1 report and item identity', 'Serious-defect escalation process', 'LOLER vs PUWER scope', 'Travel, access, VAT and re-examination', 'Total comparable fee'],
    acceptance: ['Every examined item has a traceable identity and location', 'Examination trigger and interval are correct for the use', 'Safety-critical parts and relevant tests are recorded', 'Defects explain the danger and required action', 'Immediate-danger findings were communicated promptly', 'Schedule 1 report fields are complete', 'Next examination date or scheme reference is explicit', 'Maintenance and defect closure remain separate and tracked'],
    source: 'https://www.hse.gov.uk/pubns/indg422.pdf', sourceLabel: 'HSE INDG422',
  },
} as const

export function ServiceBuyingToolkit({ serviceId }: { serviceId: IndustrialServiceId }) {
  const definition = serviceDefinitions[serviceId]
  const data = toolkitData[serviceId]
  return <article className="content-page toolkit-page">
    <header className="content-hero"><div className="shell narrow"><span className="eyebrow">Buyer pack · version 1.0</span><h1>{data.title}</h1><p className="lead">{data.lead}</p><ToolkitActions /></div></header>
    <div className="shell toolkit-summary"><section className="decision-panel"><span className="eyebrow">The standard</span><h2>A comparable quote must answer five things</h2><ol>{data.standard.map((item) => <li key={item}>{item}</li>)}</ol></section></div>
    <div className="shell toolkit-sections">
      <section className="toolkit-sheet"><div className="sheet-number">01</div><div><h2>Information to assemble before requesting quotes</h2><p>Mark unknown items explicitly. Discovery can be priced; hidden assumptions cannot be compared.</p><ul className="checklist">{data.assemble.map((item) => <Check key={item}>{item}</Check>)}</ul></div></section>
      <section className="toolkit-sheet"><div className="sheet-number">02</div><div><h2>Project brief</h2><div className="brief-fields"><p><strong>Business and site:</strong> ______________________________________________</p><p><strong>Reason for commissioning:</strong> first / periodic / new installation / change or event</p><p><strong>Equipment and identifiers:</strong> ______________________________________</p><p><strong>Use, process or operating conditions:</strong> ______________________________</p><p><strong>Documents available:</strong> ___________________________________________</p><p><strong>Sites and areas in scope:</strong> ________________________________________</p><p><strong>Access and shutdown constraints:</strong> _________________________________</p><p><strong>Target visit and report date:</strong> _____________________________________</p></div><h3>Required quotation format</h3><ul className="checklist">{data.standard.map((item) => <Check key={item}>{item}</Check>)}</ul></div></section>
      <section className="toolkit-sheet"><div className="sheet-number">03</div><div><h2>Competence and evidence questions</h2><p>Competence is specific to the equipment, system and judgement being bought. Ask about the proposed person, not only the company.</p><ol className="question-list">{data.competence.map((item) => <li key={item}>{item}</li>)}</ol></div></section>
      <section className="toolkit-sheet landscape-sheet"><div className="sheet-number">04</div><div><h2>Comparable quote scorecard</h2><div className="table-scroll"><table className="comparison-table"><thead><tr><th>Comparison point</th><th>Provider A</th><th>Provider B</th><th>Provider C</th></tr></thead><tbody>{data.comparison.map((row) => <tr key={row}><th>{row}</th><td></td><td></td><td></td></tr>)}</tbody></table></div><p className="toolkit-warning"><strong>Do not add the scores blindly.</strong> Missing competence, equipment scope or statutory reporting can be a stop condition rather than a small disadvantage.</p></div></section>
      <section className="toolkit-sheet"><div className="sheet-number">05</div><div><h2>Report acceptance check</h2><ul className="checklist">{data.acceptance.map((item) => <Check key={item}>{item}</Check>)}</ul><p>Primary basis: <a href={data.source} target="_blank" rel="noreferrer">{data.sourceLabel} <span aria-hidden>↗</span></a>.</p></div></section>
    </div>
    <div className="shell toolkit-footer-note"><p><strong>Vendor Atlas {definition.shortName} buyer standard v1.0 · 31 August 2026.</strong> This pack is procurement support, not a statutory examination, legal advice or competence certification. Adapt it to the equipment and risk.</p><Link href={definition.supplierPath}>Browse the evidence directory →</Link></div>
  </article>
}
