import {
  AirVent,
  CircleGauge,
  Factory,
  Fan,
  FileCheck2,
  Filter,
  Gauge,
  HardHat,
  Link2,
  PackageCheck,
  SearchCheck,
  ShieldCheck,
  UserRound,
  Wind,
  Wrench,
  type LucideIcon,
} from 'lucide-react'
import type { ServiceId } from '../domain/types'

type IndustrialServiceId = Exclude<ServiceId, 'dsear'>
type Node = { title: string; detail: string; icon: LucideIcon }

const diagrams: Record<IndustrialServiceId, { eyebrow: string; title: string; intro: string; nodes: Node[]; evidence: string[]; source: string; sourceLabel: string }> = {
  lev: {
    eyebrow: 'System map', title: 'What a complete LEV examination follows', intro: 'A TExT follows the contaminant from capture to discharge and tests whether the complete control chain still performs as intended.',
    nodes: [
      { title: 'Source', detail: 'Dust, fume, mist or vapour generated by the work', icon: Factory },
      { title: 'Hood', detail: 'Capture position, enclosure and control at the source', icon: AirVent },
      { title: 'Duct', detail: 'Condition, transport velocity, leakage and test points', icon: Wind },
      { title: 'Cleaner', detail: 'Filter or collector condition and pressure behaviour', icon: Filter },
      { title: 'Fan & discharge', detail: 'Air mover, exhaust route and any recirculation risk', icon: Fan },
    ],
    evidence: ['Physical condition', 'Airflow and pressure measurements', 'Benchmark comparison', 'Control judgement and actions'], source: 'https://books.hse.gov.uk/gempdf/hsg258.pdf', sourceLabel: 'HSE HSG258',
  },
  'pressure-systems': {
    eyebrow: 'Duty sequence', title: 'The pressure system comes before the paperwork', intro: 'First define the real safety-critical system. The written scheme then controls what is examined, how and when.',
    nodes: [
      { title: 'Relevant fluid', detail: 'Steam, compressed gas or another in-scope fluid', icon: CircleGauge },
      { title: 'System boundary', detail: 'Vessels, associated pipework and connected plant', icon: Link2 },
      { title: 'Protective devices', detail: 'Safety valves and devices protecting against danger', icon: ShieldCheck },
      { title: 'Written scheme', detail: 'Parts, examination nature, preparation and intervals', icon: FileCheck2 },
      { title: 'Examination', detail: 'Competent-person work, report and danger actions', icon: SearchCheck },
    ],
    evidence: ['Safe operating limits', 'Equipment and device inventory', 'Suitable certified scheme', 'Examination report and actions'], source: 'https://www.hse.gov.uk/pubns/indg178.htm', sourceLabel: 'HSE INDG178',
  },
  loler: {
    eyebrow: 'Interval map', title: 'Classify the asset before assigning a due date', intro: 'The normal maximum interval follows what the item is and how it is used. A competent-person scheme or an exceptional event can change the route.',
    nodes: [
      { title: 'Lifts people', detail: 'Normally examine at least every six months', icon: UserRound },
      { title: 'Lifting accessory', detail: 'Normally examine at least every six months', icon: PackageCheck },
      { title: 'Other lifting equipment', detail: 'Normally examine at least every twelve months', icon: HardHat },
      { title: 'Examination scheme', detail: 'A competent person may specify different intervals', icon: FileCheck2 },
      { title: 'Exceptional event', detail: 'Damage, repair, relocation or long disuse can trigger examination', icon: Wrench },
    ],
    evidence: ['Item identity and lifting use', 'Installation and event history', 'Equipment-specific competent person', 'Schedule 1 report and defect action'], source: 'https://www.hse.gov.uk/work-equipment-machinery/thorough-examinations-lifting-equipment.htm', sourceLabel: 'HSE thorough-examination guidance',
  },
}

export function TechnicalDiagram({ serviceId }: { serviceId: IndustrialServiceId }) {
  const diagram = diagrams[serviceId]
  return <section className={`technical-diagram technical-diagram-${serviceId}`} aria-labelledby={`${serviceId}-diagram-title`}>
    <div className="technical-diagram-copy"><span className="eyebrow">{diagram.eyebrow}</span><h2 id={`${serviceId}-diagram-title`}>{diagram.title}</h2><p>{diagram.intro}</p><a href={diagram.source} target="_blank" rel="noreferrer">Check against {diagram.sourceLabel} <span aria-hidden>↗</span></a></div>
    <ol className="technical-flow">{diagram.nodes.map(({ title, detail, icon: Icon }, index) => <li key={title}><span className="technical-node-icon" aria-hidden="true"><Icon strokeWidth={1.75} /></span><span className="technical-node-number">{String(index + 1).padStart(2, '0')}</span><strong>{title}</strong><small>{detail}</small></li>)}</ol>
    <div className="technical-evidence"><span><Gauge aria-hidden="true" /> Evidence a competent appointment should leave visible</span><ul>{diagram.evidence.map((item) => <li key={item}>{item}</li>)}</ul></div>
  </section>
}
