import {
  AirVent,
  CircleGauge,
  Factory,
  Fan,
  FileCheck2,
  Filter,
  Gauge,
  HardHat,
  Link2,
  PackageCheck,
  SearchCheck,
  ShieldCheck,
  UserRound,
  Wind,
  Wrench,
  type LucideIcon,
} from 'lucide-react'
import type { ServiceId } from '../domain/types'

type IndustrialServiceId = Exclude<ServiceId, 'dsear'>
type Node = { title: string; detail: string; icon: LucideIcon }

const diagrams: Record<IndustrialServiceId, { eyebrow: string; title: string; intro: string; nodes: Node[]; evidence: string[]; source: string; sourceLabel: string }> = {
  lev: {
    eyebrow: 'System map', title: 'What a complete LEV examination follows', intro: 'A TExT follows the contaminant from capture to discharge and tests whether the complete control chain still performs as intended.',
    nodes: [
      { title: 'Source', detail: 'Dust, fume, mist or vapour generated by the work', icon: Factory },
      { title: 'Hood', detail: 'Capture position, enclosure and control at the source', icon: AirVent },
      { title: 'Duct', detail: 'Condition, transport velocity, leakage and test points', icon: Wind },
      { title: 'Cleaner', detail: 'Filter or collector condition and pressure behaviour', icon: Filter },
      { title: 'Fan & discharge', detail: 'Air mover, exhaust route and any recirculation risk', icon: Fan },
    ],
    evidence: ['Physical condition', 'Airflow and pressure measurements', 'Benchmark comparison', 'Control judgement and actions'], source: 'https://books.hse.gov.uk/gempdf/hsg258.pdf', sourceLabel: 'HSE HSG258',
  },
  'pressure-systems': {
    eyebrow: 'Duty sequence', title: 'The pressure system comes before the paperwork', intro: 'First define the real safety-critical system. The written scheme then controls what is examined, how and when.',
    nodes: [
      { title: 'Relevant fluid', detail: 'Steam, compressed gas or another in-scope fluid', icon: CircleGauge },
      { title: 'System boundary', detail: 'Vessels, associated pipework and connected plant', icon: Link2 },
      { title: 'Protective devices', detail: 'Safety valves and devices protecting against danger', icon: ShieldCheck },
      { title: 'Written scheme', detail: 'Parts, examination nature, preparation and intervals', icon: FileCheck2 },
      { title: 'Examination', detail: 'Competent-person work, report and danger actions', icon: SearchCheck },
    ],
    evidence: ['Safe operating limits', 'Equipment and device inventory', 'Suitable certified scheme', 'Examination report and actions'], source: 'https://www.hse.gov.uk/pubns/indg178.htm', sourceLabel: 'HSE INDG178',
  },
  loler: {
    eyebrow: 'Interval map', title: 'Classify the asset before assigning a due date', intro: 'The normal maximum interval follows what the item is and how it is used. A competent-person scheme or an exceptional event can change the route.',
    nodes: [
      { title: 'Lifts people', detail: 'Normally examine at least every six months', icon: UserRound },
      { title: 'Lifting accessory', detail: 'Normally examine at least every six months', icon: PackageCheck },
      { title: 'Other lifting equipment', detail: 'Normally examine at least every twelve months', icon: HardHat },
      { title: 'Examination scheme', detail: 'A competent person may specify different intervals', icon: FileCheck2 },
      { title: 'Exceptional event', detail: 'Damage, repair, relocation or long disuse can trigger examination', icon: Wrench },
    ],
    evidence: ['Item identity and lifting use', 'Installation and event history', 'Equipment-specific competent person', 'Schedule 1 report and defect action'], source: 'https://www.hse.gov.uk/work-equipment-machinery/thorough-examinations-lifting-equipment.htm', sourceLabel: 'HSE thorough-examination guidance',
  },
  asbestos: {
    eyebrow: 'Survey route', title: 'The building decision sets the survey depth', intro: 'The dutyholder, premises records and planned disturbance determine what must be inspected and how the result will be used.',
    nodes: [
      { title: 'Premises', detail: 'Dutyholder, building age, areas and maintenance responsibility', icon: Factory },
      { title: 'Decision', detail: 'Normal management, refurbishment, demolition or reinspection', icon: SearchCheck },
      { title: 'Survey plan', detail: 'Access, exclusions, intrusion, samples and safe working method', icon: FileCheck2 },
      { title: 'Findings', detail: 'Location, extent, condition, analysis and assessment', icon: PackageCheck },
      { title: 'Control', detail: 'Live register, management actions or project work controls', icon: ShieldCheck },
    ],
    evidence: ['Defined scope and exclusions', 'Sample and laboratory traceability', 'Marked locations and assessments', 'Register or project actions'], source: 'https://www.hse.gov.uk/pubns/priced/hsg264.pdf', sourceLabel: 'HSE HSG264',
  },
  'fire-risk-assessment': {
    eyebrow: 'Assessment sequence', title: 'Five steps connect hazards to managed action', intro: 'The Home Office sequence starts with the real premises and people, then records evaluated precautions, actions and review triggers.',
    nodes: [
      { title: 'Fire hazards', detail: 'Ignition, fuel, oxygen, processes and dangerous substances', icon: Factory },
      { title: 'People at risk', detail: 'Occupants, visitors, lone workers and people needing assistance', icon: UserRound },
      { title: 'Evaluate and act', detail: 'Escape, warning, protection and risk reduction', icon: SearchCheck },
      { title: 'Record and plan', detail: 'Significant findings, emergency plan, information and training', icon: FileCheck2 },
      { title: 'Review', detail: 'Recheck after change, doubt, fire, near miss or other trigger', icon: ShieldCheck },
    ],
    evidence: ['Premises and responsible-person scope', 'People and hazard findings', 'Evaluated fire precautions', 'Prioritised actions and review record'], source: 'https://www.gov.uk/government/publications/fire-safety-risk-assessment-5-step-checklist/fire-safety-risk-assessment-5-step-checklist-accessible', sourceLabel: 'Home Office five-step checklist',
  },
  legionella: {
    eyebrow: 'Control sequence', title: 'Assessment connects water assets to operating controls', intro: 'The responsible person needs a mapped system, evidence of risk conditions and a written scheme that defines what happens between assessments.',
    nodes: [
      { title: 'Water source', detail: 'Mains, storage, heating, cooling or process supply', icon: Factory },
      { title: 'System assets', detail: 'Tanks, calorifiers, loops, pipework and outlets', icon: Link2 },
      { title: 'Exposure', detail: 'Aerosols, system users and susceptible people', icon: UserRound },
      { title: 'Controls', detail: 'Temperature, turnover, cleaning, monitoring and action limits', icon: ShieldCheck },
      { title: 'Written scheme', detail: 'Named duties, tasks, records, corrective action and review', icon: FileCheck2 },
    ],
    evidence: ['System schematic and asset register', 'Risk and exposure findings', 'Control measurements and records', 'Written scheme and corrective actions'], source: 'https://www.hse.gov.uk/pubns/priced/l8.pdf', sourceLabel: 'HSE ACOP L8',
  },
  'pat-testing': {
    eyebrow: 'Maintenance sequence', title: 'Equipment risk sets the check and interval', intro: 'The maintenance decision starts with equipment, use and environment, then selects checks capable of finding the foreseeable defects.',
    nodes: [
      { title: 'Inventory', detail: 'Owner, location, equipment type, class and condition', icon: PackageCheck },
      { title: 'Risk group', detail: 'Movement, environment, users and fault history', icon: SearchCheck },
      { title: 'User check', detail: 'Visible damage and safe reporting before or during use', icon: UserRound },
      { title: 'Inspect or test', detail: 'Formal visual checks and suitable measurements where needed', icon: Gauge },
      { title: 'Act and review', detail: 'Isolate defects, keep records and change intervals using results', icon: ShieldCheck },
    ],
    evidence: ['Equipment scope and risk groups', 'Inspection and test method', 'Itemised results and exclusions', 'Defect actions and reviewed intervals'], source: 'https://www.hse.gov.uk/electricity/faq-portable-appliance-testing.htm', sourceLabel: 'HSE PAT guidance',
  },
}

export function TechnicalDiagram({ serviceId }: { serviceId: IndustrialServiceId }) {
  const diagram = diagrams[serviceId]
  return <section className={`technical-diagram technical-diagram-${serviceId}`} aria-labelledby={`${serviceId}-diagram-title`}>
    <div className="technical-diagram-copy"><span className="eyebrow">{diagram.eyebrow}</span><h2 id={`${serviceId}-diagram-title`}>{diagram.title}</h2><p>{diagram.intro}</p><a href={diagram.source} target="_blank" rel="noreferrer">Check against {diagram.sourceLabel} <span aria-hidden>↗</span></a></div>
    <ol className="technical-flow">{diagram.nodes.map(({ title, detail, icon: Icon }, index) => <li key={title}><span className="technical-node-icon" aria-hidden="true"><Icon strokeWidth={1.75} /></span><span className="technical-node-number">{String(index + 1).padStart(2, '0')}</span><strong>{title}</strong><small>{detail}</small></li>)}</ol>
    <div className="technical-evidence"><span><Gauge aria-hidden="true" /> Evidence a competent appointment should leave visible</span><ul>{diagram.evidence.map((item) => <li key={item}>{item}</li>)}</ul></div>
  </section>
}
